name: Perl FSM Regression
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: '5.32'
    - name: Set up mdBook
      uses: peaceiris/actions-mdbook@v2
    - name: Run shared regression CI script
      run: ./bin/ci-regression
