-- Flattened Decision Tree FSM: ahb_lite_subordinate
-- Generated by FSMGen direct VHDL scaffold
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity ahb_lite_subordinate is
  port (
    clk : in std_logic;
    rst_n : in std_logic;
    HADDR : in std_logic_vector(31 downto 0);
    HREADY : in std_logic;
    HSEL : in std_logic;
    HSIZE : in std_logic_vector(2 downto 0);
    HTRANS : in std_logic_vector(1 downto 0);
    HWDATA : in std_logic_vector(31 downto 0);
    HWRITE : in std_logic;
    wait_cycles : in std_logic_vector(3 downto 0);
    HRDATA : out std_logic_vector(31 downto 0);
    HREADYOUT : out std_logic;
    HRESP : out std_logic
  );
end entity ahb_lite_subordinate;

architecture rtl of ahb_lite_subordinate is
  constant AHB_LITE_ACCESS_IDLE_0 : std_logic_vector(4 downto 0) := "00000";
  constant AHB_LITE_ACCESS_SET_1 : std_logic_vector(4 downto 0) := "00001";
  constant AHB_LITE_ACCESS_DRIVE_2 : std_logic_vector(4 downto 0) := "00010";
  constant AHB_LITE_ACCESS_REPEAT_INIT_3 : std_logic_vector(4 downto 0) := "00011";
  constant AHB_LITE_ACCESS_WAIT_4 : std_logic_vector(4 downto 0) := "00100";
  constant AHB_LITE_ACCESS_REPEAT_CHECK_5 : std_logic_vector(4 downto 0) := "00101";
  constant AHB_LITE_ACCESS_WHEN_6 : std_logic_vector(4 downto 0) := "00110";
  constant AHB_LITE_ACCESS_DRIVE_7 : std_logic_vector(4 downto 0) := "00111";
  constant AHB_LITE_ACCESS_DRIVE_8 : std_logic_vector(4 downto 0) := "01000";
  constant AHB_LITE_ACCESS_WHEN_9 : std_logic_vector(4 downto 0) := "01001";
  constant AHB_LITE_ACCESS_DRIVE_10 : std_logic_vector(4 downto 0) := "01010";
  constant AHB_LITE_ACCESS_DRIVE_11 : std_logic_vector(4 downto 0) := "01011";
  constant AHB_LITE_ACCESS_WHEN_12 : std_logic_vector(4 downto 0) := "01100";
  constant AHB_LITE_ACCESS_DRIVE_13 : std_logic_vector(4 downto 0) := "01101";
  constant AHB_LITE_ACCESS_DRIVE_14 : std_logic_vector(4 downto 0) := "01110";
  constant AHB_LITE_ACCESS_WHEN_15 : std_logic_vector(4 downto 0) := "01111";
  constant AHB_LITE_ACCESS_SET_16 : std_logic_vector(4 downto 0) := "10000";
  constant AHB_LITE_ACCESS_DRIVE_17 : std_logic_vector(4 downto 0) := "10001";
  constant AHB_LITE_ACCESS_WHEN_18 : std_logic_vector(4 downto 0) := "10010";
  constant AHB_LITE_ACCESS_DRIVE_19 : std_logic_vector(4 downto 0) := "10011";
  constant AHB_LITE_ACCESS_DONE_20 : std_logic_vector(4 downto 0) := "10100";

  signal current_state : std_logic_vector(4 downto 0);
  signal next_state : std_logic_vector(4 downto 0);
  signal addr_q : std_logic_vector(31 downto 0);
  signal ahb_access_done_q : std_logic;
  signal ahb_lite_access_cnt : std_logic_vector(3 downto 0);
  signal ahb_phase_pending_q : std_logic;
  signal can_accept : std_logic;
  signal enter_data_phase_start : std_logic;
  signal error_complete_start : std_logic;
  signal error_first_start : std_logic;
  signal next_addr_q : std_logic_vector(31 downto 0);
  signal next_size_q : std_logic_vector(2 downto 0);
  signal next_trans_q : std_logic_vector(1 downto 0);
  signal next_wait_n : std_logic_vector(3 downto 0);
  signal next_write_q : std_logic;
  signal read_hit_start : std_logic;
  signal reg_data_q : std_logic_vector(31 downto 0);
  signal size_q : std_logic_vector(2 downto 0);
  signal trans_q : std_logic_vector(1 downto 0);
  signal wait_n : std_logic_vector(3 downto 0);
  signal write_hit_start : std_logic;
  signal write_q : std_logic;
  signal HRDATA_next : std_logic_vector(31 downto 0);
  signal HREADYOUT_next : std_logic;
  signal HRESP_next : std_logic;
  signal addr_q_q : std_logic_vector(31 downto 0);
  signal ahb_access_done_q_pulse_delay_pipe : std_logic;
  signal ahb_lite_access_cnt_next : std_logic_vector(3 downto 0);
  signal ahb_phase_pending_q_next : std_logic;
  signal next_addr_q_next : std_logic_vector(31 downto 0);
  signal next_size_q_next : std_logic_vector(2 downto 0);
  signal next_trans_q_next : std_logic_vector(1 downto 0);
  signal next_wait_n_next : std_logic_vector(3 downto 0);
  signal next_write_q_next : std_logic;
  signal reg_data_q_next : std_logic_vector(31 downto 0);
  signal size_q_q : std_logic_vector(2 downto 0);
  signal trans_q_q : std_logic_vector(1 downto 0);
  signal wait_n_q : std_logic_vector(3 downto 0);
  signal write_q_q : std_logic;
  signal addr_q_next_addr_q_en : std_logic;
  signal ahb_access_done_q_1_en : std_logic;
  signal ahb_error_retire_en : std_logic;
  signal ahb_error_retire_hreadyout_1_en : std_logic;
  signal ahb_error_retire_hresp_1_b0_en : std_logic;
  signal ahb_lite_access_cnt_expr_en : std_logic;
  signal ahb_lite_access_cnt_wait_n_en : std_logic;
  signal ahb_lite_access_done_20_ahb_access_done_q_1_en : std_logic;
  signal ahb_lite_access_done_20_en : std_logic;
  signal ahb_lite_access_done_20_next_state_ahb_lite_access_idle_0_en : std_logic;
  signal ahb_lite_access_drive_10_en : std_logic;
  signal ahb_lite_access_drive_10_error_first_start_1_en : std_logic;
  signal ahb_lite_access_drive_10_next_state_ahb_lite_access_drive_11_en : std_logic;
  signal ahb_lite_access_drive_11_en : std_logic;
  signal ahb_lite_access_drive_11_error_complete_start_1_en : std_logic;
  signal ahb_lite_access_drive_11_next_state_ahb_lite_access_when_12_en : std_logic;
  signal ahb_lite_access_drive_13_en : std_logic;
  signal ahb_lite_access_drive_13_error_first_start_1_en : std_logic;
  signal ahb_lite_access_drive_13_next_state_ahb_lite_access_drive_14_en : std_logic;
  signal ahb_lite_access_drive_14_en : std_logic;
  signal ahb_lite_access_drive_14_error_complete_start_1_en : std_logic;
  signal ahb_lite_access_drive_14_next_state_ahb_lite_access_when_15_en : std_logic;
  signal ahb_lite_access_drive_17_en : std_logic;
  signal ahb_lite_access_drive_17_next_state_ahb_lite_access_when_18_en : std_logic;
  signal ahb_lite_access_drive_17_write_hit_start_1_en : std_logic;
  signal ahb_lite_access_drive_19_en : std_logic;
  signal ahb_lite_access_drive_19_next_state_ahb_lite_access_done_20_en : std_logic;
  signal ahb_lite_access_drive_19_read_hit_start_1_en : std_logic;
  signal ahb_lite_access_drive_2_en : std_logic;
  signal ahb_lite_access_drive_2_enter_data_phase_start_1_en : std_logic;
  signal ahb_lite_access_drive_2_next_state_ahb_lite_access_repeat_init_3_en : std_logic;
  signal ahb_lite_access_drive_7_en : std_logic;
  signal ahb_lite_access_drive_7_error_first_start_1_en : std_logic;
  signal ahb_lite_access_drive_7_next_state_ahb_lite_access_drive_8_en : std_logic;
  signal ahb_lite_access_drive_8_en : std_logic;
  signal ahb_lite_access_drive_8_error_complete_start_1_en : std_logic;
  signal ahb_lite_access_drive_8_next_state_ahb_lite_access_when_9_en : std_logic;
  signal ahb_lite_access_idle_0_addr_q_next_addr_q_en : std_logic;
  signal ahb_lite_access_idle_0_can_accept_1_en : std_logic;
  signal ahb_lite_access_idle_0_en : std_logic;
  signal ahb_lite_access_idle_0_hrdata_0_en : std_logic;
  signal ahb_lite_access_idle_0_hreadyout_1_en : std_logic;
  signal ahb_lite_access_idle_0_hresp_0_en : std_logic;
  signal ahb_lite_access_idle_0_next_state_ahb_lite_access_set_1_en : std_logic;
  signal ahb_lite_access_idle_0_size_q_next_size_q_en : std_logic;
  signal ahb_lite_access_idle_0_trans_q_next_trans_q_en : std_logic;
  signal ahb_lite_access_idle_0_wait_n_next_wait_n_en : std_logic;
  signal ahb_lite_access_idle_0_write_q_next_write_q_en : std_logic;
  signal ahb_lite_access_repeat_check_5_ahb_lite_access_cnt_ahb_lite_access_cnt_1_en : std_logic;
  signal ahb_lite_access_repeat_check_5_en : std_logic;
  signal ahb_lite_access_repeat_check_5_next_state_ahb_lite_access_wait_4_en : std_logic;
  signal ahb_lite_access_repeat_check_5_next_state_ahb_lite_access_when_6_en : std_logic;
  signal ahb_lite_access_repeat_init_3_ahb_lite_access_cnt_wait_n_en : std_logic;
  signal ahb_lite_access_repeat_init_3_en : std_logic;
  signal ahb_lite_access_repeat_init_3_next_state_ahb_lite_access_repeat_check_5_en : std_logic;
  signal ahb_lite_access_set_16_en : std_logic;
  signal ahb_lite_access_set_16_next_state_ahb_lite_access_drive_17_en : std_logic;
  signal ahb_lite_access_set_16_reg_data_q_hwdata_en : std_logic;
  signal ahb_lite_access_set_1_ahb_phase_pending_q_0_en : std_logic;
  signal ahb_lite_access_set_1_en : std_logic;
  signal ahb_lite_access_set_1_next_state_ahb_lite_access_drive_2_en : std_logic;
  signal ahb_lite_access_wait_4_en : std_logic;
  signal ahb_lite_access_wait_4_next_state_ahb_lite_access_repeat_check_5_en : std_logic;
  signal ahb_lite_access_when_12_en : std_logic;
  signal ahb_lite_access_when_12_next_state_ahb_lite_access_drive_13_en : std_logic;
  signal ahb_lite_access_when_12_next_state_ahb_lite_access_when_15_en : std_logic;
  signal ahb_lite_access_when_15_en : std_logic;
  signal ahb_lite_access_when_15_next_state_ahb_lite_access_set_16_en : std_logic;
  signal ahb_lite_access_when_15_next_state_ahb_lite_access_when_18_en : std_logic;
  signal ahb_lite_access_when_18_en : std_logic;
  signal ahb_lite_access_when_18_next_state_ahb_lite_access_done_20_en : std_logic;
  signal ahb_lite_access_when_18_next_state_ahb_lite_access_drive_19_en : std_logic;
  signal ahb_lite_access_when_6_en : std_logic;
  signal ahb_lite_access_when_6_next_state_ahb_lite_access_drive_7_en : std_logic;
  signal ahb_lite_access_when_6_next_state_ahb_lite_access_when_9_en : std_logic;
  signal ahb_lite_access_when_9_en : std_logic;
  signal ahb_lite_access_when_9_next_state_ahb_lite_access_drive_10_en : std_logic;
  signal ahb_lite_access_when_9_next_state_ahb_lite_access_when_12_en : std_logic;
  signal ahb_phase_capture_ahb_phase_pending_q_1_en : std_logic;
  signal ahb_phase_capture_en : std_logic;
  signal ahb_phase_capture_hreadyout_0_en : std_logic;
  signal ahb_phase_capture_next_addr_q_haddr_en : std_logic;
  signal ahb_phase_capture_next_size_q_hsize_en : std_logic;
  signal ahb_phase_capture_next_trans_q_htrans_en : std_logic;
  signal ahb_phase_capture_next_wait_n_wait_cycles_en : std_logic;
  signal ahb_phase_capture_next_write_q_hwrite_en : std_logic;
  signal ahb_phase_hold_en : std_logic;
  signal ahb_phase_hold_hreadyout_0_en : std_logic;
  signal ahb_phase_pending_q_0_en : std_logic;
  signal ahb_phase_pending_q_1_en : std_logic;
  signal can_accept_1_en : std_logic;
  signal enter_data_phase_en : std_logic;
  signal enter_data_phase_hrdata_0_en : std_logic;
  signal enter_data_phase_hreadyout_0_en : std_logic;
  signal enter_data_phase_hresp_1_b0_en : std_logic;
  signal enter_data_phase_start_1_en : std_logic;
  signal error_complete_en : std_logic;
  signal error_complete_hrdata_0_en : std_logic;
  signal error_complete_hreadyout_1_en : std_logic;
  signal error_complete_hresp_1_b1_en : std_logic;
  signal error_complete_start_1_en : std_logic;
  signal error_first_en : std_logic;
  signal error_first_hrdata_0_en : std_logic;
  signal error_first_hreadyout_0_en : std_logic;
  signal error_first_hresp_1_b1_en : std_logic;
  signal error_first_start_1_en : std_logic;
  signal hrdata_0_en : std_logic;
  signal hrdata_reg_data_q_en : std_logic;
  signal hreadyout_0_en : std_logic;
  signal hreadyout_1_en : std_logic;
  signal hresp_0_en : std_logic;
  signal hresp_1_b0_en : std_logic;
  signal hresp_1_b1_en : std_logic;
  signal next_addr_q_haddr_en : std_logic;
  signal next_size_q_hsize_en : std_logic;
  signal next_state_ahb_lite_access_done_20_en : std_logic;
  signal next_state_ahb_lite_access_drive_10_en : std_logic;
  signal next_state_ahb_lite_access_drive_11_en : std_logic;
  signal next_state_ahb_lite_access_drive_13_en : std_logic;
  signal next_state_ahb_lite_access_drive_14_en : std_logic;
  signal next_state_ahb_lite_access_drive_17_en : std_logic;
  signal next_state_ahb_lite_access_drive_19_en : std_logic;
  signal next_state_ahb_lite_access_drive_2_en : std_logic;
  signal next_state_ahb_lite_access_drive_7_en : std_logic;
  signal next_state_ahb_lite_access_drive_8_en : std_logic;
  signal next_state_ahb_lite_access_idle_0_en : std_logic;
  signal next_state_ahb_lite_access_repeat_check_5_en : std_logic;
  signal next_state_ahb_lite_access_repeat_init_3_en : std_logic;
  signal next_state_ahb_lite_access_set_16_en : std_logic;
  signal next_state_ahb_lite_access_set_1_en : std_logic;
  signal next_state_ahb_lite_access_wait_4_en : std_logic;
  signal next_state_ahb_lite_access_when_12_en : std_logic;
  signal next_state_ahb_lite_access_when_15_en : std_logic;
  signal next_state_ahb_lite_access_when_18_en : std_logic;
  signal next_state_ahb_lite_access_when_6_en : std_logic;
  signal next_state_ahb_lite_access_when_9_en : std_logic;
  signal next_trans_q_htrans_en : std_logic;
  signal next_wait_n_wait_cycles_en : std_logic;
  signal next_write_q_hwrite_en : std_logic;
  signal read_hit_en : std_logic;
  signal read_hit_hrdata_reg_data_q_en : std_logic;
  signal read_hit_hreadyout_1_en : std_logic;
  signal read_hit_hresp_1_b0_en : std_logic;
  signal read_hit_start_1_en : std_logic;
  signal reg_data_q_hwdata_en : std_logic;
  signal size_q_next_size_q_en : std_logic;
  signal trans_q_next_trans_q_en : std_logic;
  signal wait_n_next_wait_n_en : std_logic;
  signal write_hit_en : std_logic;
  signal write_hit_hrdata_0_en : std_logic;
  signal write_hit_hreadyout_1_en : std_logic;
  signal write_hit_hresp_1_b0_en : std_logic;
  signal write_hit_start_1_en : std_logic;
  signal write_q_next_write_q_en : std_logic;
  signal HREADYOUT_and_HRESP : std_logic;
  signal HTRANS_eq_const_10 : std_logic;
  signal HTRANS_eq_const_11 : std_logic;
  signal intermediate_and_HREADYOUT_14 : std_logic;
  signal intermediate_and_HREADYOUT_25 : std_logic;
  signal intermediate_and_HREADYOUT_31 : std_logic;
  signal intermediate_and_HREADYOUT_4 : std_logic;
  signal intermediate_and_not_write_q_11 : std_logic;
  signal intermediate_and_write_q_10 : std_logic;
  signal intermediate_complex_expr_1 : std_logic;
  signal intermediate_complex_expr_12 : std_logic;
  signal intermediate_complex_expr_15 : std_logic;
  signal intermediate_complex_expr_18 : std_logic;
  signal intermediate_complex_expr_22 : std_logic;
  signal intermediate_complex_expr_27 : std_logic;
  signal intermediate_complex_expr_33 : std_logic;
  signal intermediate_complex_expr_36 : std_logic;
  signal intermediate_complex_expr_5 : std_logic;
  signal intermediate_complex_expr_7 : std_logic;
  signal intermediate_complex_expr_8 : std_logic;
  signal intermediate_complex_expr_9 : std_logic;
  signal not_ahb_phase_pending_q : std_logic;
  signal size_q_eq_const_2 : std_logic;
  signal trans_q_eq_const_10 : std_logic;
  signal HTRANS_eq_const_10_or_HTRANS_eq_const_11 : std_logic;
  signal intermediate_and_error_complete_start_not_intermediat_etc_26 : std_logic;
  signal intermediate_and_error_first_start_not_intermediate_a_etc_32 : std_logic;
  signal not_intermediate_and_HREADYOUT_4 : std_logic;
  signal intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_2 : std_logic;
  signal intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_13 : std_logic;
  signal intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_16 : std_logic;
  signal intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_19 : std_logic;
  signal intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_23 : std_logic;
  signal intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_28 : std_logic;
  signal intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_34 : std_logic;
  signal intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_37 : std_logic;
  signal intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_6 : std_logic;
  signal not_ahb_phase_pending_q_and_HSEL : std_logic;
  signal trans_q_eq_const_10_and_size_q_eq_const_2 : std_logic;
  signal intermediate_and_not_intermediate_and_not_ahb_phase_p_etc_3 : std_logic;
  signal intermediate_and_not_intermediate_and_not_ahb_phase_p_etc_17 : std_logic;
  signal intermediate_and_HREADYOUT_not_intermediate_and_not_a_etc_20 : std_logic;
  signal intermediate_and_error_complete_start_not_intermediat_etc_24 : std_logic;
  signal intermediate_and_HREADYOUT_not_intermediate_and_not_a_etc_29 : std_logic;
  signal intermediate_and_read_hit_start_not_intermediate_and_etc_35 : std_logic;
  signal intermediate_and_write_hit_start_not_intermediate_and_etc_38 : std_logic;
  signal not_intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_6 : std_logic;
  signal not_ahb_phase_pending_q_and_HSEL_and_HREADY : std_logic;
  signal trans_q_eq_const_10_and_size_q_eq_const_2_and_not_addr_q : std_logic;
  signal intermediate_and_enter_data_phase_start_not_intermedi_etc_21 : std_logic;
  signal intermediate_and_error_first_start_not_intermediate_a_etc_30 : std_logic;

  function fsmgen_direct_vhdl_reduce_or(value : std_logic_vector) return std_logic is
    variable result : std_logic := '0';
  begin
    for index in value'range loop
      result := result or value(index);
    end loop;
    return result;
  end function fsmgen_direct_vhdl_reduce_or;
begin

  ahb_lite_access_done_20_en <= '1' when current_state = AHB_LITE_ACCESS_DONE_20 else '0';
  ahb_lite_access_drive_10_en <= '1' when current_state = AHB_LITE_ACCESS_DRIVE_10 else '0';
  ahb_lite_access_drive_11_en <= '1' when current_state = AHB_LITE_ACCESS_DRIVE_11 else '0';
  ahb_lite_access_drive_13_en <= '1' when current_state = AHB_LITE_ACCESS_DRIVE_13 else '0';
  ahb_lite_access_drive_14_en <= '1' when current_state = AHB_LITE_ACCESS_DRIVE_14 else '0';
  ahb_lite_access_drive_17_en <= '1' when current_state = AHB_LITE_ACCESS_DRIVE_17 else '0';
  ahb_lite_access_drive_19_en <= '1' when current_state = AHB_LITE_ACCESS_DRIVE_19 else '0';
  ahb_lite_access_drive_2_en <= '1' when current_state = AHB_LITE_ACCESS_DRIVE_2 else '0';
  ahb_lite_access_drive_7_en <= '1' when current_state = AHB_LITE_ACCESS_DRIVE_7 else '0';
  ahb_lite_access_drive_8_en <= '1' when current_state = AHB_LITE_ACCESS_DRIVE_8 else '0';
  ahb_lite_access_idle_0_en <= '1' when current_state = AHB_LITE_ACCESS_IDLE_0 else '0';
  ahb_lite_access_repeat_check_5_en <= '1' when current_state = AHB_LITE_ACCESS_REPEAT_CHECK_5 else '0';
  ahb_lite_access_repeat_init_3_en <= '1' when current_state = AHB_LITE_ACCESS_REPEAT_INIT_3 else '0';
  ahb_lite_access_set_1_en <= '1' when current_state = AHB_LITE_ACCESS_SET_1 else '0';
  ahb_lite_access_set_16_en <= '1' when current_state = AHB_LITE_ACCESS_SET_16 else '0';
  ahb_lite_access_wait_4_en <= '1' when current_state = AHB_LITE_ACCESS_WAIT_4 else '0';
  ahb_lite_access_when_12_en <= '1' when current_state = AHB_LITE_ACCESS_WHEN_12 else '0';
  ahb_lite_access_when_15_en <= '1' when current_state = AHB_LITE_ACCESS_WHEN_15 else '0';
  ahb_lite_access_when_18_en <= '1' when current_state = AHB_LITE_ACCESS_WHEN_18 else '0';
  ahb_lite_access_when_6_en <= '1' when current_state = AHB_LITE_ACCESS_WHEN_6 else '0';
  ahb_lite_access_when_9_en <= '1' when current_state = AHB_LITE_ACCESS_WHEN_9 else '0';
  ahb_error_retire_en <= intermediate_and_HREADYOUT_14;
  ahb_phase_capture_en <= intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_13;
  ahb_phase_hold_en <= (ahb_phase_pending_q);
  enter_data_phase_en <= '1';
  error_complete_en <= '1';
  error_first_en <= '1';
  read_hit_en <= '1';
  write_hit_en <= '1';
  HREADYOUT_and_HRESP <= HREADYOUT and HRESP;
  HTRANS_eq_const_10 <= '1' when HTRANS = "10" else '0';
  HTRANS_eq_const_11 <= '1' when HTRANS = "11" else '0';
  intermediate_and_HREADYOUT_14 <= HREADYOUT and HRESP;
  intermediate_and_HREADYOUT_25 <= HREADYOUT and HRESP;
  intermediate_and_HREADYOUT_31 <= HREADYOUT and HRESP;
  intermediate_and_HREADYOUT_4 <= HREADYOUT and HRESP;
  intermediate_and_not_write_q_11 <= '1' when (trans_q = "10") and (size_q = "010") and (fsmgen_direct_vhdl_reduce_or(addr_q) = '0') and (write_q = '0') else '0';
  intermediate_and_write_q_10 <= '1' when (trans_q = "10") and (size_q = "010") and (fsmgen_direct_vhdl_reduce_or(addr_q) = '0') and (write_q = '1') else '0';
  intermediate_complex_expr_1 <= '1' when (HTRANS = "10") or (HTRANS = "11") else '0';
  intermediate_complex_expr_12 <= '1' when (HTRANS = "10") or (HTRANS = "11") else '0';
  intermediate_complex_expr_15 <= '1' when (HTRANS = "10") or (HTRANS = "11") else '0';
  intermediate_complex_expr_18 <= '1' when (HTRANS = "10") or (HTRANS = "11") else '0';
  intermediate_complex_expr_22 <= '1' when (HTRANS = "10") or (HTRANS = "11") else '0';
  intermediate_complex_expr_27 <= '1' when (HTRANS = "10") or (HTRANS = "11") else '0';
  intermediate_complex_expr_33 <= '1' when (HTRANS = "10") or (HTRANS = "11") else '0';
  intermediate_complex_expr_36 <= '1' when (HTRANS = "10") or (HTRANS = "11") else '0';
  intermediate_complex_expr_5 <= '1' when (HTRANS = "10") or (HTRANS = "11") else '0';
  intermediate_complex_expr_7 <= '1' when trans_q = "11" else '0';
  intermediate_complex_expr_8 <= '1' when (trans_q = "10") and not ((size_q = "010")) else '0';
  intermediate_complex_expr_9 <= '1' when (trans_q = "10") and (size_q = "010") and not (fsmgen_direct_vhdl_reduce_or(addr_q) = '0') else '0';
  not_ahb_phase_pending_q <= (not ahb_phase_pending_q);
  size_q_eq_const_2 <= '1' when size_q = "010" else '0';
  trans_q_eq_const_10 <= '1' when trans_q = "10" else '0';
  HTRANS_eq_const_10_or_HTRANS_eq_const_11 <= HTRANS_eq_const_10 or HTRANS_eq_const_11;
  intermediate_and_error_complete_start_not_intermediat_etc_26 <= error_complete_start and not intermediate_and_HREADYOUT_25;
  intermediate_and_error_first_start_not_intermediate_a_etc_32 <= error_first_start and not intermediate_and_HREADYOUT_31;
  not_intermediate_and_HREADYOUT_4 <= not intermediate_and_HREADYOUT_4;
  intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_2 <= (not ahb_phase_pending_q) and HSEL and HREADY and intermediate_complex_expr_1;
  intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_13 <= (not ahb_phase_pending_q) and HSEL and HREADY and intermediate_complex_expr_12;
  intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_16 <= (not ahb_phase_pending_q) and HSEL and HREADY and intermediate_complex_expr_15;
  intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_19 <= (not ahb_phase_pending_q) and HSEL and HREADY and intermediate_complex_expr_18;
  intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_23 <= (not ahb_phase_pending_q) and HSEL and HREADY and intermediate_complex_expr_22;
  intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_28 <= (not ahb_phase_pending_q) and HSEL and HREADY and intermediate_complex_expr_27;
  intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_34 <= (not ahb_phase_pending_q) and HSEL and HREADY and intermediate_complex_expr_33;
  intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_37 <= (not ahb_phase_pending_q) and HSEL and HREADY and intermediate_complex_expr_36;
  intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_6 <= (not ahb_phase_pending_q) and HSEL and HREADY and intermediate_complex_expr_5;
  not_ahb_phase_pending_q_and_HSEL <= not_ahb_phase_pending_q and HSEL;
  trans_q_eq_const_10_and_size_q_eq_const_2 <= trans_q_eq_const_10 and size_q_eq_const_2;
  intermediate_and_not_intermediate_and_not_ahb_phase_p_etc_3 <= not intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_2 and (not ahb_phase_pending_q);
  intermediate_and_not_intermediate_and_not_ahb_phase_p_etc_17 <= not intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_16 and (not ahb_phase_pending_q);
  intermediate_and_HREADYOUT_not_intermediate_and_not_a_etc_20 <= HREADYOUT and HRESP and not intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_19 and (not ahb_phase_pending_q);
  intermediate_and_error_complete_start_not_intermediat_etc_24 <= error_complete_start and not intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_23 and (not ahb_phase_pending_q);
  intermediate_and_HREADYOUT_not_intermediate_and_not_a_etc_29 <= HREADYOUT and HRESP and not intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_28 and (not ahb_phase_pending_q);
  intermediate_and_read_hit_start_not_intermediate_and_etc_35 <= read_hit_start and not intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_34 and (not ahb_phase_pending_q);
  intermediate_and_write_hit_start_not_intermediate_and_etc_38 <= write_hit_start and not intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_37 and (not ahb_phase_pending_q);
  not_intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_6 <= not intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_6;
  not_ahb_phase_pending_q_and_HSEL_and_HREADY <= not_ahb_phase_pending_q_and_HSEL and HREADY;
  trans_q_eq_const_10_and_size_q_eq_const_2_and_not_addr_q <= trans_q_eq_const_10_and_size_q_eq_const_2 and (not fsmgen_direct_vhdl_reduce_or(addr_q));
  intermediate_and_enter_data_phase_start_not_intermedi_etc_21 <= enter_data_phase_start and not intermediate_and_HREADYOUT_not_intermediate_and_not_a_etc_20;
  intermediate_and_error_first_start_not_intermediate_a_etc_30 <= error_first_start and not intermediate_and_HREADYOUT_not_intermediate_and_not_a_etc_29;
  ahb_error_retire_hreadyout_1_en <= ahb_error_retire_en and intermediate_and_not_intermediate_and_not_ahb_phase_p_etc_17;
  ahb_error_retire_hresp_1_b0_en <= ahb_error_retire_en;
  ahb_phase_capture_hreadyout_0_en <= ahb_phase_capture_en;
  ahb_phase_capture_ahb_phase_pending_q_1_en <= ahb_phase_capture_en;
  ahb_phase_capture_next_addr_q_haddr_en <= ahb_phase_capture_en;
  ahb_phase_capture_next_size_q_hsize_en <= ahb_phase_capture_en;
  ahb_phase_capture_next_trans_q_htrans_en <= ahb_phase_capture_en;
  ahb_phase_capture_next_wait_n_wait_cycles_en <= ahb_phase_capture_en;
  ahb_phase_capture_next_write_q_hwrite_en <= ahb_phase_capture_en;
  ahb_phase_hold_hreadyout_0_en <= ahb_phase_hold_en;
  enter_data_phase_hrdata_0_en <= enter_data_phase_en and (enter_data_phase_start);
  enter_data_phase_hreadyout_0_en <= enter_data_phase_en and intermediate_and_enter_data_phase_start_not_intermedi_etc_21;
  enter_data_phase_hresp_1_b0_en <= enter_data_phase_en and (enter_data_phase_start);
  error_complete_hrdata_0_en <= error_complete_en and (error_complete_start);
  error_complete_hreadyout_1_en <= error_complete_en and intermediate_and_error_complete_start_not_intermediat_etc_24;
  error_complete_hresp_1_b1_en <= error_complete_en and intermediate_and_error_complete_start_not_intermediat_etc_26;
  error_first_hrdata_0_en <= error_first_en and (error_first_start);
  error_first_hreadyout_0_en <= error_first_en and intermediate_and_error_first_start_not_intermediate_a_etc_30;
  error_first_hresp_1_b1_en <= error_first_en and intermediate_and_error_first_start_not_intermediate_a_etc_32;
  read_hit_hrdata_reg_data_q_en <= read_hit_en and (read_hit_start);
  read_hit_hreadyout_1_en <= read_hit_en and intermediate_and_read_hit_start_not_intermediate_and_etc_35;
  read_hit_hresp_1_b0_en <= read_hit_en and (read_hit_start);
  write_hit_hrdata_0_en <= write_hit_en and (write_hit_start);
  write_hit_hreadyout_1_en <= write_hit_en and intermediate_and_write_hit_start_not_intermediate_and_etc_38;
  write_hit_hresp_1_b0_en <= write_hit_en and (write_hit_start);
  ahb_lite_access_done_20_ahb_access_done_q_1_en <= ahb_lite_access_done_20_en;
  ahb_lite_access_done_20_next_state_ahb_lite_access_idle_0_en <= ahb_lite_access_done_20_en;
  ahb_lite_access_drive_10_error_first_start_1_en <= ahb_lite_access_drive_10_en;
  ahb_lite_access_drive_10_next_state_ahb_lite_access_drive_11_en <= ahb_lite_access_drive_10_en;
  ahb_lite_access_drive_11_error_complete_start_1_en <= ahb_lite_access_drive_11_en;
  ahb_lite_access_drive_11_next_state_ahb_lite_access_when_12_en <= ahb_lite_access_drive_11_en;
  ahb_lite_access_drive_13_error_first_start_1_en <= ahb_lite_access_drive_13_en;
  ahb_lite_access_drive_13_next_state_ahb_lite_access_drive_14_en <= ahb_lite_access_drive_13_en;
  ahb_lite_access_drive_14_error_complete_start_1_en <= ahb_lite_access_drive_14_en;
  ahb_lite_access_drive_14_next_state_ahb_lite_access_when_15_en <= ahb_lite_access_drive_14_en;
  ahb_lite_access_drive_17_next_state_ahb_lite_access_when_18_en <= ahb_lite_access_drive_17_en;
  ahb_lite_access_drive_17_write_hit_start_1_en <= ahb_lite_access_drive_17_en;
  ahb_lite_access_drive_19_next_state_ahb_lite_access_done_20_en <= ahb_lite_access_drive_19_en;
  ahb_lite_access_drive_19_read_hit_start_1_en <= ahb_lite_access_drive_19_en;
  ahb_lite_access_drive_2_enter_data_phase_start_1_en <= ahb_lite_access_drive_2_en;
  ahb_lite_access_drive_2_next_state_ahb_lite_access_repeat_init_3_en <= ahb_lite_access_drive_2_en;
  ahb_lite_access_drive_7_error_first_start_1_en <= ahb_lite_access_drive_7_en;
  ahb_lite_access_drive_7_next_state_ahb_lite_access_drive_8_en <= ahb_lite_access_drive_7_en;
  ahb_lite_access_drive_8_error_complete_start_1_en <= ahb_lite_access_drive_8_en;
  ahb_lite_access_drive_8_next_state_ahb_lite_access_when_9_en <= ahb_lite_access_drive_8_en;
  ahb_lite_access_idle_0_hrdata_0_en <= ahb_lite_access_idle_0_en;
  ahb_lite_access_idle_0_hreadyout_1_en <= ahb_lite_access_idle_0_en and intermediate_and_not_intermediate_and_not_ahb_phase_p_etc_3;
  ahb_lite_access_idle_0_hresp_0_en <= ahb_lite_access_idle_0_en and not_intermediate_and_HREADYOUT_4;
  ahb_lite_access_idle_0_addr_q_next_addr_q_en <= ahb_lite_access_idle_0_en and (ahb_phase_pending_q);
  ahb_lite_access_idle_0_can_accept_1_en <= ahb_lite_access_idle_0_en;
  ahb_lite_access_idle_0_next_state_ahb_lite_access_set_1_en <= ahb_lite_access_idle_0_en and (ahb_phase_pending_q);
  ahb_lite_access_idle_0_size_q_next_size_q_en <= ahb_lite_access_idle_0_en and (ahb_phase_pending_q);
  ahb_lite_access_idle_0_trans_q_next_trans_q_en <= ahb_lite_access_idle_0_en and (ahb_phase_pending_q);
  ahb_lite_access_idle_0_wait_n_next_wait_n_en <= ahb_lite_access_idle_0_en and (ahb_phase_pending_q);
  ahb_lite_access_idle_0_write_q_next_write_q_en <= ahb_lite_access_idle_0_en and (ahb_phase_pending_q);
  ahb_lite_access_repeat_check_5_ahb_lite_access_cnt_ahb_lite_access_cnt_1_en <= ahb_lite_access_repeat_check_5_en;
  ahb_lite_access_repeat_check_5_next_state_ahb_lite_access_wait_4_en <= ahb_lite_access_repeat_check_5_en and (fsmgen_direct_vhdl_reduce_or(ahb_lite_access_cnt));
  ahb_lite_access_repeat_check_5_next_state_ahb_lite_access_when_6_en <= ahb_lite_access_repeat_check_5_en and (not fsmgen_direct_vhdl_reduce_or(ahb_lite_access_cnt));
  ahb_lite_access_repeat_init_3_ahb_lite_access_cnt_wait_n_en <= ahb_lite_access_repeat_init_3_en;
  ahb_lite_access_repeat_init_3_next_state_ahb_lite_access_repeat_check_5_en <= ahb_lite_access_repeat_init_3_en;
  ahb_lite_access_set_1_ahb_phase_pending_q_0_en <= ahb_lite_access_set_1_en and not_intermediate_and_not_ahb_phase_pending_q_HSEL_HREADY_etc_6;
  ahb_lite_access_set_1_next_state_ahb_lite_access_drive_2_en <= ahb_lite_access_set_1_en;
  ahb_lite_access_set_16_next_state_ahb_lite_access_drive_17_en <= ahb_lite_access_set_16_en;
  ahb_lite_access_set_16_reg_data_q_hwdata_en <= ahb_lite_access_set_16_en;
  ahb_lite_access_wait_4_next_state_ahb_lite_access_repeat_check_5_en <= ahb_lite_access_wait_4_en;
  ahb_lite_access_when_12_next_state_ahb_lite_access_drive_13_en <= ahb_lite_access_when_12_en and intermediate_complex_expr_9;
  ahb_lite_access_when_12_next_state_ahb_lite_access_when_15_en <= ahb_lite_access_when_12_en and not intermediate_complex_expr_9;
  ahb_lite_access_when_15_next_state_ahb_lite_access_set_16_en <= ahb_lite_access_when_15_en and intermediate_and_write_q_10;
  ahb_lite_access_when_15_next_state_ahb_lite_access_when_18_en <= ahb_lite_access_when_15_en and not intermediate_and_write_q_10;
  ahb_lite_access_when_18_next_state_ahb_lite_access_done_20_en <= ahb_lite_access_when_18_en and not intermediate_and_not_write_q_11;
  ahb_lite_access_when_18_next_state_ahb_lite_access_drive_19_en <= ahb_lite_access_when_18_en and intermediate_and_not_write_q_11;
  ahb_lite_access_when_6_next_state_ahb_lite_access_drive_7_en <= ahb_lite_access_when_6_en and intermediate_complex_expr_7;
  ahb_lite_access_when_6_next_state_ahb_lite_access_when_9_en <= ahb_lite_access_when_6_en and not intermediate_complex_expr_7;
  ahb_lite_access_when_9_next_state_ahb_lite_access_drive_10_en <= ahb_lite_access_when_9_en and intermediate_complex_expr_8;
  ahb_lite_access_when_9_next_state_ahb_lite_access_when_12_en <= ahb_lite_access_when_9_en and not intermediate_complex_expr_8;
  hrdata_0_en <= (((enter_data_phase_hrdata_0_en or error_complete_hrdata_0_en) or error_first_hrdata_0_en) or write_hit_hrdata_0_en) or ahb_lite_access_idle_0_hrdata_0_en;
  hrdata_reg_data_q_en <= read_hit_hrdata_reg_data_q_en;
  hreadyout_0_en <= ((ahb_phase_capture_hreadyout_0_en or ahb_phase_hold_hreadyout_0_en) or enter_data_phase_hreadyout_0_en) or error_first_hreadyout_0_en;
  hreadyout_1_en <= (((ahb_error_retire_hreadyout_1_en or error_complete_hreadyout_1_en) or read_hit_hreadyout_1_en) or write_hit_hreadyout_1_en) or ahb_lite_access_idle_0_hreadyout_1_en;
  hresp_0_en <= ahb_lite_access_idle_0_hresp_0_en;
  hresp_1_b0_en <= ((ahb_error_retire_hresp_1_b0_en or enter_data_phase_hresp_1_b0_en) or read_hit_hresp_1_b0_en) or write_hit_hresp_1_b0_en;
  hresp_1_b1_en <= error_complete_hresp_1_b1_en or error_first_hresp_1_b1_en;
  addr_q_next_addr_q_en <= ahb_lite_access_idle_0_addr_q_next_addr_q_en;
  ahb_access_done_q_1_en <= ahb_lite_access_done_20_ahb_access_done_q_1_en;
  ahb_lite_access_cnt_expr_en <= ahb_lite_access_repeat_check_5_ahb_lite_access_cnt_ahb_lite_access_cnt_1_en;
  ahb_lite_access_cnt_wait_n_en <= ahb_lite_access_repeat_init_3_ahb_lite_access_cnt_wait_n_en;
  ahb_phase_pending_q_0_en <= ahb_lite_access_set_1_ahb_phase_pending_q_0_en;
  ahb_phase_pending_q_1_en <= ahb_phase_capture_ahb_phase_pending_q_1_en;
  can_accept_1_en <= ahb_lite_access_idle_0_can_accept_1_en;
  enter_data_phase_start_1_en <= ahb_lite_access_drive_2_enter_data_phase_start_1_en;
  error_complete_start_1_en <= (ahb_lite_access_drive_11_error_complete_start_1_en or ahb_lite_access_drive_14_error_complete_start_1_en) or ahb_lite_access_drive_8_error_complete_start_1_en;
  error_first_start_1_en <= (ahb_lite_access_drive_10_error_first_start_1_en or ahb_lite_access_drive_13_error_first_start_1_en) or ahb_lite_access_drive_7_error_first_start_1_en;
  next_addr_q_haddr_en <= ahb_phase_capture_next_addr_q_haddr_en;
  next_size_q_hsize_en <= ahb_phase_capture_next_size_q_hsize_en;
  next_state_ahb_lite_access_done_20_en <= ahb_lite_access_drive_19_next_state_ahb_lite_access_done_20_en or ahb_lite_access_when_18_next_state_ahb_lite_access_done_20_en;
  next_state_ahb_lite_access_drive_10_en <= ahb_lite_access_when_9_next_state_ahb_lite_access_drive_10_en;
  next_state_ahb_lite_access_drive_11_en <= ahb_lite_access_drive_10_next_state_ahb_lite_access_drive_11_en;
  next_state_ahb_lite_access_drive_13_en <= ahb_lite_access_when_12_next_state_ahb_lite_access_drive_13_en;
  next_state_ahb_lite_access_drive_14_en <= ahb_lite_access_drive_13_next_state_ahb_lite_access_drive_14_en;
  next_state_ahb_lite_access_drive_17_en <= ahb_lite_access_set_16_next_state_ahb_lite_access_drive_17_en;
  next_state_ahb_lite_access_drive_19_en <= ahb_lite_access_when_18_next_state_ahb_lite_access_drive_19_en;
  next_state_ahb_lite_access_drive_2_en <= ahb_lite_access_set_1_next_state_ahb_lite_access_drive_2_en;
  next_state_ahb_lite_access_drive_7_en <= ahb_lite_access_when_6_next_state_ahb_lite_access_drive_7_en;
  next_state_ahb_lite_access_drive_8_en <= ahb_lite_access_drive_7_next_state_ahb_lite_access_drive_8_en;
  next_state_ahb_lite_access_idle_0_en <= ahb_lite_access_done_20_next_state_ahb_lite_access_idle_0_en;
  next_state_ahb_lite_access_repeat_check_5_en <= ahb_lite_access_repeat_init_3_next_state_ahb_lite_access_repeat_check_5_en or ahb_lite_access_wait_4_next_state_ahb_lite_access_repeat_check_5_en;
  next_state_ahb_lite_access_repeat_init_3_en <= ahb_lite_access_drive_2_next_state_ahb_lite_access_repeat_init_3_en;
  next_state_ahb_lite_access_set_1_en <= ahb_lite_access_idle_0_next_state_ahb_lite_access_set_1_en;
  next_state_ahb_lite_access_set_16_en <= ahb_lite_access_when_15_next_state_ahb_lite_access_set_16_en;
  next_state_ahb_lite_access_wait_4_en <= ahb_lite_access_repeat_check_5_next_state_ahb_lite_access_wait_4_en;
  next_state_ahb_lite_access_when_12_en <= ahb_lite_access_drive_11_next_state_ahb_lite_access_when_12_en or ahb_lite_access_when_9_next_state_ahb_lite_access_when_12_en;
  next_state_ahb_lite_access_when_15_en <= ahb_lite_access_drive_14_next_state_ahb_lite_access_when_15_en or ahb_lite_access_when_12_next_state_ahb_lite_access_when_15_en;
  next_state_ahb_lite_access_when_18_en <= ahb_lite_access_drive_17_next_state_ahb_lite_access_when_18_en or ahb_lite_access_when_15_next_state_ahb_lite_access_when_18_en;
  next_state_ahb_lite_access_when_6_en <= ahb_lite_access_repeat_check_5_next_state_ahb_lite_access_when_6_en;
  next_state_ahb_lite_access_when_9_en <= ahb_lite_access_drive_8_next_state_ahb_lite_access_when_9_en or ahb_lite_access_when_6_next_state_ahb_lite_access_when_9_en;
  next_trans_q_htrans_en <= ahb_phase_capture_next_trans_q_htrans_en;
  next_wait_n_wait_cycles_en <= ahb_phase_capture_next_wait_n_wait_cycles_en;
  next_write_q_hwrite_en <= ahb_phase_capture_next_write_q_hwrite_en;
  read_hit_start_1_en <= ahb_lite_access_drive_19_read_hit_start_1_en;
  reg_data_q_hwdata_en <= ahb_lite_access_set_16_reg_data_q_hwdata_en;
  size_q_next_size_q_en <= ahb_lite_access_idle_0_size_q_next_size_q_en;
  trans_q_next_trans_q_en <= ahb_lite_access_idle_0_trans_q_next_trans_q_en;
  wait_n_next_wait_n_en <= ahb_lite_access_idle_0_wait_n_next_wait_n_en;
  write_hit_start_1_en <= ahb_lite_access_drive_17_write_hit_start_1_en;
  write_q_next_write_q_en <= ahb_lite_access_idle_0_write_q_next_write_q_en;

  process(clk, rst_n) begin
    if rst_n = '0' then
      current_state <= AHB_LITE_ACCESS_IDLE_0;
    elsif rising_edge(clk) then
      current_state <= next_state;
    end if;
  end process;

  process(all) begin
    HRDATA_next <= HRDATA;
    if hrdata_0_en = '1' then
      HRDATA_next <= std_logic_vector(to_unsigned(0, 32));
    end if;
    if hrdata_reg_data_q_en = '1' then
      HRDATA_next <= reg_data_q;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      HRDATA <= "00000000000000000000000000000000";
    elsif rising_edge(clk) then
      HRDATA <= HRDATA_next;
    end if;
  end process;

  process(all) begin
    HREADYOUT_next <= HREADYOUT;
    if hreadyout_0_en = '1' then
      HREADYOUT_next <= '0';
    end if;
    if hreadyout_1_en = '1' then
      HREADYOUT_next <= '1';
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      HREADYOUT <= '1';
    elsif rising_edge(clk) then
      HREADYOUT <= HREADYOUT_next;
    end if;
  end process;

  process(all) begin
    HRESP_next <= HRESP;
    if hresp_0_en = '1' then
      HRESP_next <= '0';
    end if;
    if hresp_1_b0_en = '1' then
      HRESP_next <= '0';
    end if;
    if hresp_1_b1_en = '1' then
      HRESP_next <= '1';
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      HRESP <= '0';
    elsif rising_edge(clk) then
      HRESP <= HRESP_next;
    end if;
  end process;

  process(all) begin
    addr_q <= addr_q_q;
    if addr_q_next_addr_q_en = '1' then
      addr_q <= next_addr_q;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      addr_q_q <= "00000000000000000000000000000000";
    elsif rising_edge(clk) then
      addr_q_q <= addr_q;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      ahb_access_done_q <= '0';
      ahb_access_done_q_pulse_delay_pipe <= '0';
    elsif rising_edge(clk) then
      ahb_access_done_q <= '0';
      if ahb_access_done_q_pulse_delay_pipe = '1' then
        ahb_access_done_q <= '1';
      end if;
      ahb_access_done_q_pulse_delay_pipe <= ahb_access_done_q_1_en;
    end if;
  end process;

  process(all) begin
    ahb_lite_access_cnt_next <= ahb_lite_access_cnt;
    if ahb_lite_access_cnt_expr_en = '1' then
      ahb_lite_access_cnt_next <= std_logic_vector(unsigned(ahb_lite_access_cnt) - to_unsigned(1, 4));
    end if;
    if ahb_lite_access_cnt_wait_n_en = '1' then
      ahb_lite_access_cnt_next <= wait_n;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      ahb_lite_access_cnt <= "0000";
    elsif rising_edge(clk) then
      ahb_lite_access_cnt <= ahb_lite_access_cnt_next;
    end if;
  end process;

  process(all) begin
    ahb_phase_pending_q_next <= ahb_phase_pending_q;
    if ahb_phase_pending_q_0_en = '1' then
      ahb_phase_pending_q_next <= '0';
    end if;
    if ahb_phase_pending_q_1_en = '1' then
      ahb_phase_pending_q_next <= '1';
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      ahb_phase_pending_q <= '0';
    elsif rising_edge(clk) then
      ahb_phase_pending_q <= ahb_phase_pending_q_next;
    end if;
  end process;

  process(all) begin
    can_accept <= '0';
    if can_accept_1_en = '1' then
      can_accept <= '1';
    end if;
  end process;

  process(all) begin
    enter_data_phase_start <= '0';
    if enter_data_phase_start_1_en = '1' then
      enter_data_phase_start <= '1';
    end if;
  end process;

  process(all) begin
    error_complete_start <= '0';
    if error_complete_start_1_en = '1' then
      error_complete_start <= '1';
    end if;
  end process;

  process(all) begin
    error_first_start <= '0';
    if error_first_start_1_en = '1' then
      error_first_start <= '1';
    end if;
  end process;

  process(all) begin
    next_addr_q_next <= next_addr_q;
    if next_addr_q_haddr_en = '1' then
      next_addr_q_next <= HADDR;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      next_addr_q <= "00000000000000000000000000000000";
    elsif rising_edge(clk) then
      next_addr_q <= next_addr_q_next;
    end if;
  end process;

  process(all) begin
    next_size_q_next <= next_size_q;
    if next_size_q_hsize_en = '1' then
      next_size_q_next <= HSIZE;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      next_size_q <= "000";
    elsif rising_edge(clk) then
      next_size_q <= next_size_q_next;
    end if;
  end process;

  process(all) begin
    next_state <= current_state;
    if next_state_ahb_lite_access_done_20_en = '1' then
      next_state <= AHB_LITE_ACCESS_DONE_20;
    end if;
    if next_state_ahb_lite_access_drive_10_en = '1' then
      next_state <= AHB_LITE_ACCESS_DRIVE_10;
    end if;
    if next_state_ahb_lite_access_drive_11_en = '1' then
      next_state <= AHB_LITE_ACCESS_DRIVE_11;
    end if;
    if next_state_ahb_lite_access_drive_13_en = '1' then
      next_state <= AHB_LITE_ACCESS_DRIVE_13;
    end if;
    if next_state_ahb_lite_access_drive_14_en = '1' then
      next_state <= AHB_LITE_ACCESS_DRIVE_14;
    end if;
    if next_state_ahb_lite_access_drive_17_en = '1' then
      next_state <= AHB_LITE_ACCESS_DRIVE_17;
    end if;
    if next_state_ahb_lite_access_drive_19_en = '1' then
      next_state <= AHB_LITE_ACCESS_DRIVE_19;
    end if;
    if next_state_ahb_lite_access_drive_2_en = '1' then
      next_state <= AHB_LITE_ACCESS_DRIVE_2;
    end if;
    if next_state_ahb_lite_access_drive_7_en = '1' then
      next_state <= AHB_LITE_ACCESS_DRIVE_7;
    end if;
    if next_state_ahb_lite_access_drive_8_en = '1' then
      next_state <= AHB_LITE_ACCESS_DRIVE_8;
    end if;
    if next_state_ahb_lite_access_idle_0_en = '1' then
      next_state <= AHB_LITE_ACCESS_IDLE_0;
    end if;
    if next_state_ahb_lite_access_repeat_check_5_en = '1' then
      next_state <= AHB_LITE_ACCESS_REPEAT_CHECK_5;
    end if;
    if next_state_ahb_lite_access_repeat_init_3_en = '1' then
      next_state <= AHB_LITE_ACCESS_REPEAT_INIT_3;
    end if;
    if next_state_ahb_lite_access_set_1_en = '1' then
      next_state <= AHB_LITE_ACCESS_SET_1;
    end if;
    if next_state_ahb_lite_access_set_16_en = '1' then
      next_state <= AHB_LITE_ACCESS_SET_16;
    end if;
    if next_state_ahb_lite_access_wait_4_en = '1' then
      next_state <= AHB_LITE_ACCESS_WAIT_4;
    end if;
    if next_state_ahb_lite_access_when_12_en = '1' then
      next_state <= AHB_LITE_ACCESS_WHEN_12;
    end if;
    if next_state_ahb_lite_access_when_15_en = '1' then
      next_state <= AHB_LITE_ACCESS_WHEN_15;
    end if;
    if next_state_ahb_lite_access_when_18_en = '1' then
      next_state <= AHB_LITE_ACCESS_WHEN_18;
    end if;
    if next_state_ahb_lite_access_when_6_en = '1' then
      next_state <= AHB_LITE_ACCESS_WHEN_6;
    end if;
    if next_state_ahb_lite_access_when_9_en = '1' then
      next_state <= AHB_LITE_ACCESS_WHEN_9;
    end if;
  end process;

  process(all) begin
    next_trans_q_next <= next_trans_q;
    if next_trans_q_htrans_en = '1' then
      next_trans_q_next <= HTRANS;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      next_trans_q <= "00";
    elsif rising_edge(clk) then
      next_trans_q <= next_trans_q_next;
    end if;
  end process;

  process(all) begin
    next_wait_n_next <= next_wait_n;
    if next_wait_n_wait_cycles_en = '1' then
      next_wait_n_next <= wait_cycles;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      next_wait_n <= "0000";
    elsif rising_edge(clk) then
      next_wait_n <= next_wait_n_next;
    end if;
  end process;

  process(all) begin
    next_write_q_next <= next_write_q;
    if next_write_q_hwrite_en = '1' then
      next_write_q_next <= HWRITE;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      next_write_q <= '0';
    elsif rising_edge(clk) then
      next_write_q <= next_write_q_next;
    end if;
  end process;

  process(all) begin
    read_hit_start <= '0';
    if read_hit_start_1_en = '1' then
      read_hit_start <= '1';
    end if;
  end process;

  process(all) begin
    reg_data_q_next <= reg_data_q;
    if reg_data_q_hwdata_en = '1' then
      reg_data_q_next <= HWDATA;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      reg_data_q <= "00000000000000000000000000000000";
    elsif rising_edge(clk) then
      reg_data_q <= reg_data_q_next;
    end if;
  end process;

  process(all) begin
    size_q <= size_q_q;
    if size_q_next_size_q_en = '1' then
      size_q <= next_size_q;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      size_q_q <= "000";
    elsif rising_edge(clk) then
      size_q_q <= size_q;
    end if;
  end process;

  process(all) begin
    trans_q <= trans_q_q;
    if trans_q_next_trans_q_en = '1' then
      trans_q <= next_trans_q;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      trans_q_q <= "00";
    elsif rising_edge(clk) then
      trans_q_q <= trans_q;
    end if;
  end process;

  process(all) begin
    wait_n <= wait_n_q;
    if wait_n_next_wait_n_en = '1' then
      wait_n <= next_wait_n;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      wait_n_q <= "0000";
    elsif rising_edge(clk) then
      wait_n_q <= wait_n;
    end if;
  end process;

  process(all) begin
    write_hit_start <= '0';
    if write_hit_start_1_en = '1' then
      write_hit_start <= '1';
    end if;
  end process;

  process(all) begin
    write_q <= write_q_q;
    if write_q_next_write_q_en = '1' then
      write_q <= next_write_q;
    end if;
  end process;

  process(clk, rst_n) begin
    if rst_n = '0' then
      write_q_q <= '0';
    elsif rising_edge(clk) then
      write_q_q <= write_q;
    end if;
  end process;

end architecture rtl;
