-- Generated by FSM::VIAL::Backend::VHDLOSVVM2026_05 revision 1.
-- OSVVM services are isolated native/supplementary mappings. Portable VIAL
-- scheduling, replay, comparison, coverage, trace, and result meaning remain
-- authoritative and are byte-identical to vhdl_portable_ghdl.
library ieee;
use ieee.std_logic_1164.all;

library osvvm;
context osvvm.OsvvmContext;

library osvvm_common;

package fsmgen_vial_osvvm_adapter_pkg is
  constant FSMGEN_VIAL_OSVVM_VERSION : string := "2026.05";
  constant FSMGEN_VIAL_OSVVM_SCOREBOARD_BASIS : string :=
    "osvvm.ScoreboardGenericPkg via osvvm.ScoreboardPkg_slv";

  subtype fsmgen_vial_osvvm_scoreboard_id_t is
    osvvm.ScoreboardPkg_slv.ScoreboardIDType;
  subtype fsmgen_vial_osvvm_coverage_id_t is
    osvvm.CoveragePkg.CoverageIDType;
  subtype fsmgen_vial_osvvm_barrier_t is
    osvvm.TbUtilPkg.BarrierType;
  subtype fsmgen_vial_osvvm_memory_id_t is
    osvvm.MemoryPkg.MemoryIDType;
  subtype fsmgen_vial_osvvm_address_bus_t is
    osvvm_common.AddressBusTransactionPkg.AddressBusRecType;

  procedure fsmgen_osvvm_native_random(
    variable generator : inout osvvm.RandomPkg.RandomPType;
    constant minimum : in integer;
    constant maximum : in integer;
    variable value : out integer
  );

  procedure fsmgen_osvvm_coverage_sample(
    constant coverage_id : in fsmgen_vial_osvvm_coverage_id_t;
    constant point : in integer
  );

  procedure fsmgen_osvvm_scoreboard_expect(
    constant scoreboard_id : in fsmgen_vial_osvvm_scoreboard_id_t;
    constant expected : in std_logic_vector
  );

  procedure fsmgen_osvvm_scoreboard_check(
    constant scoreboard_id : in fsmgen_vial_osvvm_scoreboard_id_t;
    constant actual : in std_logic_vector
  );

  procedure fsmgen_osvvm_affirm(
    constant condition : in boolean;
    constant message : in string
  );

  procedure fsmgen_osvvm_wait_for_barrier(
    signal barrier : inout fsmgen_vial_osvvm_barrier_t
  );

  impure function fsmgen_osvvm_new_memory(
    constant name : in string;
    constant address_width : in positive;
    constant data_width : in positive
  ) return fsmgen_vial_osvvm_memory_id_t;

  procedure fsmgen_osvvm_memory_write(
    constant memory_id : in fsmgen_vial_osvvm_memory_id_t;
    constant address_value : in std_logic_vector;
    constant data_value : in std_logic_vector
  );
end package;

package body fsmgen_vial_osvvm_adapter_pkg is
  procedure fsmgen_osvvm_native_random(
    variable generator : inout osvvm.RandomPkg.RandomPType;
    constant minimum : in integer;
    constant maximum : in integer;
    variable value : out integer
  ) is
  begin
    value := generator.Uniform(minimum, maximum);
  end procedure;

  procedure fsmgen_osvvm_coverage_sample(
    constant coverage_id : in fsmgen_vial_osvvm_coverage_id_t;
    constant point : in integer
  ) is
  begin
    osvvm.CoveragePkg.ICover(coverage_id, point);
  end procedure;

  procedure fsmgen_osvvm_scoreboard_expect(
    constant scoreboard_id : in fsmgen_vial_osvvm_scoreboard_id_t;
    constant expected : in std_logic_vector
  ) is
  begin
    osvvm.ScoreboardPkg_slv.Push(scoreboard_id, expected);
  end procedure;

  procedure fsmgen_osvvm_scoreboard_check(
    constant scoreboard_id : in fsmgen_vial_osvvm_scoreboard_id_t;
    constant actual : in std_logic_vector
  ) is
  begin
    osvvm.ScoreboardPkg_slv.Check(scoreboard_id, actual);
  end procedure;

  procedure fsmgen_osvvm_affirm(
    constant condition : in boolean;
    constant message : in string
  ) is
  begin
    osvvm.AlertLogPkg.AffirmIf(condition, message);
  end procedure;

  procedure fsmgen_osvvm_wait_for_barrier(
    signal barrier : inout fsmgen_vial_osvvm_barrier_t
  ) is
  begin
    osvvm.TbUtilPkg.WaitForBarrier(barrier);
  end procedure;

  impure function fsmgen_osvvm_new_memory(
    constant name : in string;
    constant address_width : in positive;
    constant data_width : in positive
  ) return fsmgen_vial_osvvm_memory_id_t is
  begin
    return osvvm.MemoryPkg.NewID(name, address_width, data_width);
  end function;

  procedure fsmgen_osvvm_memory_write(
    constant memory_id : in fsmgen_vial_osvvm_memory_id_t;
    constant address_value : in std_logic_vector;
    constant data_value : in std_logic_vector
  ) is
  begin
    osvvm.MemoryPkg.MemWrite(memory_id, address_value, data_value);
  end procedure;
end package body;
