#!/usr/bin/env perl
use strict;
use warnings;
use Test::More;
use File::Spec;
use File::Temp qw(tempdir);
use FindBin;
use IPC::Cmd qw(run);
use JSON::PP qw(decode_json);

use lib File::Spec->catdir($FindBin::Bin, '..', 'perl');

use FSM::Adapter::IAL2::PPIF;

subtest 'adapter parses selected AHB subordinate byte-lane PPIF shape' => sub {
    ok(-f sample_byte_lane_ppif_path(), 'tracked runnable AHB byte-lane subordinate PPIF sample exists');

    my $result = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_byte_lane_ppif_path());

    is($result->{layer}, 'IAL2', 'AHB byte-lane subordinate adapter result stays IAL2');
    is($result->{kind}, 'protocol_intent.ahb_subordinate', 'adapter returns the AHB subordinate kind');
    is($result->{mode}, 'subordinate', 'AHB byte-lane subordinate mode is explicit');
    is($result->{report}{schema}, 'fsmgen.ial2.protocol_intent.ahb_subordinate.v1', 'report schema is selected');
    is($result->{report}{source_object}{id}, 'fsmgen-ahb-lite-subordinate-byte-lane', 'source object id is preserved');
    is($result->{report}{source_object}{intent_name}, 'ahb_lite_subordinate_byte_lane', 'source intent name is preserved');
    is($result->{report}{target_protocol}{transfer}, 'ahb_lite_byte_lane_access', 'report names selected transfer');
    is($result->{report}{layering}{direct_ial2_to_ial0}, 0, 'lowering goes through generated IAL1 before IAL0');

    my $isf = $result->{generated_ial1}{text};
    is($result->{generated_ial1}{name}, 'ahb_lite_subordinate_byte_lane.isf', 'generated IAL1 artifact is named');
    like($isf, qr/\A\(actor ahb_lite_subordinate_byte_lane\b/, 'generated IAL1 names byte-lane subordinate actor');
    like($isf, qr/\(drive read_byte_lane0_hit\s+\(HREADYOUT 1\)\s+\(HRESP 1'b0\)\s+\(HRDATA \(& reg_data_q 32'h000000ff\)\)\)/s, 'generated IAL1 zero-fills inactive byte read lanes');
    like($isf, qr/\(drive read_halfword_lane1_hit\s+\(HREADYOUT 1\)\s+\(HRESP 1'b0\)\s+\(HRDATA \(& reg_data_q 32'hffff0000\)\)\)/s, 'generated IAL1 zero-fills inactive halfword read lanes');
    like($isf, qr/\(set reg_data_q \(\| \(& reg_data_q 32'hffffff00\) \(& HWDATA 32'h000000ff\)\)\)/, 'generated IAL1 preserves inactive lanes for byte lane 0 writes');
    like($isf, qr/\(set reg_data_q \(\| \(& reg_data_q 32'h0000ffff\) \(& HWDATA 32'hffff0000\)\)\)/, 'generated IAL1 preserves inactive lanes for halfword lane 1 writes');
    like($isf, qr/\(set reg_data_q HWDATA\)/, 'generated IAL1 keeps full word writes direct');
    like($isf, qr/\(when \(& \(== trans_q 2'b10\) \(! \(\| \(== size_q 0\) \(== size_q 1\) \(== size_q 2\)\)\)\)/, 'generated IAL1 rejects unsupported HSIZE values');
    like($isf, qr/\(== \(& addr_q 32'hfffffffc\) 32'h00000000\)/, 'generated IAL1 checks bounded byte address window');
    like($isf, qr/\(== \(& addr_q 32'h00000001\) 32'h00000000\)/, 'generated IAL1 checks halfword alignment');

    is_deeply(
        sorted([keys %{$result->{generated_ial0}{files}}]),
        ['ahb_lite_subordinate_byte_lane.fsm'],
        'adapter exposes generated byte-lane AHB IAL0 .fsm file map',
    );
    my $fsm = $result->{generated_ial0}{files}{'ahb_lite_subordinate_byte_lane.fsm'};
    like($fsm, qr/\(\?fsm:ahb_lite_subordinate_byte_lane\b/, 'generated IAL0 names byte-lane subordinate FSM');
    like($fsm, qr/\(<- \(reg_data_q \(\| \(& reg_data_q 32'hffffff00\) \(& HWDATA 32'h000000ff\)\)\)\)/, 'generated IAL0 carries byte-lane write mask');
    like($fsm, qr/\(<- \(HRDATA> \(& reg_data_q 32'h0000ff00\)\) <read_byte_lane1_hit_start\)/, 'generated IAL0 carries masked byte read drive');
    like($fsm, qr/\(<- \(HRDATA> \(& reg_data_q 32'hffff0000\)\) <read_halfword_lane1_hit_start\)/, 'generated IAL0 carries masked halfword read drive');
    like($fsm, qr/\(<- \(HRESP> 1'b1\) <error_first_start\)/, 'generated IAL0 keeps first ERROR response');
    like($fsm, qr/\(<- \(HREADYOUT> 1\) <error_complete_start\)/, 'generated IAL0 keeps second ERROR completion');

    is_deeply($result->{report}{transfer}{supported_size}, [qw(byte halfword word)], 'report captures selected supported sizes');
    is($result->{report}{transfer}{lane_order}, 'little-endian', 'report captures lane ordering');
    is($result->{report}{transfer}{narrow_write}, 'preserve-inactive-lanes', 'report captures narrow-write policy');
    is($result->{report}{transfer}{narrow_read}, 'zero-fill-inactive-lanes', 'report captures narrow-read policy');
    is($result->{report}{transfer}{unaligned_access}, 'error', 'report captures unaligned access policy');
    is($result->{report}{transfer}{crossing_access}, 'error', 'report captures crossing access policy');
    is($result->{report}{narrow_transfer_policy}{supported_sizes}[0]{hsize}, "3'b000", 'report policy captures byte HSIZE encoding');
    is($result->{report}{narrow_transfer_policy}{supported_sizes}[1]{active_lane}, 'HADDR[1]', 'report policy captures halfword lane select');
    is($result->{report}{narrow_transfer_policy}{byte_lanes}[3]{mask}, "32'hff000000", 'report policy captures lane 3 mask');
    is($result->{report}{narrow_transfer_policy}{narrow_write}{policy}, 'preserve-inactive-lanes', 'report policy captures inactive-lane write preservation');
    is($result->{report}{narrow_transfer_policy}{narrow_read}{policy}, 'zero-fill-inactive-lanes', 'report policy captures inactive-lane read zero-fill');
    is($result->{report}{generated_artifacts}{hdl_entry}{entry_artifact}, 'ahb_lite_subordinate_byte_lane.fsm', 'report selects generated byte-lane subordinate .fsm as HDL entry');

    my %residue = map { $_->{id} => $_->{detail} } @{$result->{report}{unsupported_residue}};
    ok($residue{ahb_subordinate_profile_alias_deferred}, 'report keeps new .ahb alias residue explicit');
    like($residue{ahb_subordinate_optional_signal_residue}, qr/HBURST, HPROT, HMASTLOCK/, 'report keeps optional-signal residue');
    unlike($residue{ahb_subordinate_optional_signal_residue}, qr/byte lanes/, 'optional-signal residue no longer claims this bounded byte-lane behavior is deferred');
};

subtest 'malformed byte-lane AHB subordinate PPIF sources fail closed' => sub {
    my @cases = (
        [
            'missing supported halfword',
            sub {
                my $source = sample_byte_lane_ppif();
                $source =~ s/\n      \(supported-size halfword\)//;
                return $source;
            },
            qr/transfer\.supported_size must contain exactly byte, halfword, and word/,
        ],
        [
            'duplicate supported byte',
            sub {
                my $source = sample_byte_lane_ppif();
                $source =~ s/\(supported-size halfword\)/(supported-size byte)/;
                return $source;
            },
            qr/transfer\.supported_size has duplicate 'byte'/,
        ],
        [
            'unsupported lane order',
            sub {
                my $source = sample_byte_lane_ppif();
                $source =~ s/\(lane-order little-endian\)/(lane-order big-endian)/;
                return $source;
            },
            qr/transfer\.lane_order must be little-endian/,
        ],
        [
            'missing narrow-read policy',
            sub {
                my $source = sample_byte_lane_ppif();
                $source =~ s/\n      \(narrow-read zero-fill-inactive-lanes\)//;
                return $source;
            },
            qr/missing required field 'transfer\.narrow_read'/,
        ],
        [
            'unsupported unaligned access policy',
            sub {
                my $source = sample_byte_lane_ppif();
                $source =~ s/\(unaligned-access error\)/(unaligned-access allow)/;
                return $source;
            },
            qr/transfer\.unaligned_access must be error/,
        ],
    );

    for my $case (@cases) {
        my ($label, $build_source, $pattern) = @$case;
        my $ok = eval {
            FSM::Adapter::IAL2::PPIF->new()->parse_source($build_source->(), "$label.ppif");
            1;
        };
        ok(!$ok, "$label is rejected");
        like($@, $pattern, "$label diagnostic is targeted");
    }
};

subtest 'CLI checks, semantic export, schedule report, and outdir use the byte-lane path' => sub {
    my $check = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--check', '--json', sample_byte_lane_ppif_path());
    ok($check->{success}, 'strict check JSON succeeds for byte-lane AHB subordinate PPIF');
    is($check->{result}{module_name}, 'ahb_lite_subordinate_byte_lane', 'check JSON reports generated byte-lane subordinate module name');
    is($check->{support_accounting}{entry_id}, 'intent.ppif_ahb_lite_subordinate_byte_lane', 'check JSON matches byte-lane support accounting');
    is($check->{support_accounting}{source_kind}, 'ppif', 'check JSON reports PPIF source kind');
    is($check->{support_accounting}{coverage}, 'ial2_ppif_ahb_lite_subordinate_byte_lane_pipeline_cli', 'check JSON reports selected coverage key');

    my $semantic = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--emit-semantic-json', sample_byte_lane_ppif_path());
    ok($semantic->{success}, 'strict semantic JSON succeeds for byte-lane AHB subordinate PPIF');
    is($semantic->{generation_result_snapshot}{summary}{module_name}, 'ahb_lite_subordinate_byte_lane', 'semantic JSON reports generated module name');
    is($semantic->{generation_result_snapshot}{summary}{source_root_kind}, 'fsm', 'semantic JSON reports generated FSM source root');
    is($semantic->{support_accounting}{entry_id}, 'intent.ppif_ahb_lite_subordinate_byte_lane', 'semantic JSON matches byte-lane support accounting');

    my $schedule = run_json_command('./bin/fsmgen', '--quiet', '--emit-schedule-json', sample_byte_lane_ppif_path());
    is($schedule->{schema}, 'fsmgen.ial2.protocol_intent.ahb_subordinate.v1', 'schedule/report JSON exposes AHB subordinate schema');
    is($schedule->{target_protocol}{object}, 'ahb-subordinate', 'schedule/report JSON exposes AHB subordinate object');
    is($schedule->{generated_artifacts}{ial1}{name}, 'ahb_lite_subordinate_byte_lane.isf', 'schedule/report JSON exposes generated IAL1 artifact');
    is_deeply($schedule->{generated_artifacts}{ial0}{files}, ['ahb_lite_subordinate_byte_lane.fsm'], 'schedule/report JSON exposes generated IAL0 artifact');
    is_deeply($schedule->{transfer}{supported_size}, [qw(byte halfword word)], 'schedule/report JSON exposes supported sizes');
    is($schedule->{transfer}{narrow_write}, 'preserve-inactive-lanes', 'schedule/report JSON exposes narrow-write policy');
    is($schedule->{transfer}{narrow_read}, 'zero-fill-inactive-lanes', 'schedule/report JSON exposes narrow-read policy');
    is($schedule->{narrow_transfer_policy}{supported_sizes}[2]{hsize}, "3'b010", 'schedule/report JSON exposes word HSIZE policy');
    is($schedule->{narrow_transfer_policy}{byte_lanes}[0]{bits}, '[7:0]', 'schedule/report JSON exposes little-endian lane policy');

    my $tempdir = tempdir(CLEANUP => 1);
    my $outdir = File::Spec->catdir($tempdir, 'out');
    my $hdl = File::Spec->catfile($tempdir, 'ahb_lite_subordinate_byte_lane.sv');
    my ($success, undef, undef, undef, $stderr) = run(
        command => ['./bin/fsmgen', '--quiet', '--outdir', $outdir, '--output', $hdl, sample_byte_lane_ppif_path()],
    );
    ok($success, 'byte-lane AHB subordinate PPIF emits HDL and review artifacts through --outdir');
    is(join('', @{$stderr || []}), '', 'outdir generation keeps stderr clean');
    ok(-f File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane.isf'), 'outdir contains generated byte-lane IAL1 artifact');
    ok(-f File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane.fsm'), 'outdir contains generated byte-lane IAL0 artifact');
    ok(-f $hdl, 'outdir command emits selected byte-lane subordinate HDL output');
    like(slurp(File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane.isf')), qr/32'h000000ff/, 'outdir generated .isf keeps byte-lane mask');
    like(slurp(File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane.fsm')), qr/read_halfword_lane1_hit_start/, 'outdir generated .fsm keeps halfword read lane drive');
    like(slurp($hdl), qr/\bmodule\s+ahb_lite_subordinate_byte_lane\b/, 'generated HDL contains byte-lane AHB subordinate module');
};

subtest 'existing word-only AHB subordinate PPIF and .ahb alias stay unchanged at the public boundary' => sub {
    my $ppif = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_word_only_ppif_path());
    ok(!exists $ppif->{report}{transfer}{supported_size}, 'word-only PPIF report does not gain byte-lane supported-size policy');
    ok(!exists $ppif->{report}{narrow_transfer_policy}, 'word-only PPIF report does not gain narrow-transfer policy block');
    like($ppif->{generated_ial1}{text}, qr/\(when \(& \(== trans_q 2'b10\) \(! \(== size_q 2\)\)\)/, 'word-only PPIF still rejects every non-word HSIZE');
    like($ppif->{generated_ial1}{text}, qr/\(set reg_data_q HWDATA\)/, 'word-only PPIF still writes full register data directly');
    unlike($ppif->{generated_ial1}{text}, qr/read_byte_lane/, 'word-only PPIF does not gain byte-lane read drives');

    my $alias_check = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--check', '--json', sample_word_only_alias_path());
    ok($alias_check->{success}, 'existing subordinate .ahb alias still checks successfully');
    is($alias_check->{result}{module_name}, 'ahb_lite_subordinate', 'existing subordinate .ahb alias keeps module name');
    is($alias_check->{support_accounting}{entry_id}, 'intent.ahb_profile_alias_subordinate', 'existing subordinate .ahb alias keeps support identity');
    is($alias_check->{support_accounting}{coverage}, 'ial2_ahb_profile_alias_subordinate_pipeline_cli', 'existing subordinate .ahb alias keeps coverage key');
};

done_testing();

sub sample_byte_lane_ppif_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate_byte_lane.ppif');
}

sub sample_word_only_ppif_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate.ppif');
}

sub sample_word_only_alias_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate.ahb');
}

sub sample_byte_lane_ppif {
    return slurp(sample_byte_lane_ppif_path());
}

sub run_json_command {
    my @command = @_;
    my ($success, undef, undef, $stdout, $stderr) = run(command => \@command);
    my $json = join('', @{$stdout || []});
    my $decoded = eval { decode_json($json) };
    ok($decoded, join(' ', @command) . ' emits decodable JSON')
        or do {
            diag($json);
            diag(join('', @{$stderr || []}));
            diag('command failed') unless $success;
            return {};
        };
    return $decoded;
}

sub slurp {
    my ($path) = @_;
    open my $fh, '<', $path or die "Cannot read $path: $!";
    local $/;
    return <$fh>;
}

sub sorted {
    my ($values) = @_;
    return [sort @$values];
}
