#!/usr/bin/env perl
use strict;
use warnings;
use Test::More;
use File::Spec;
use File::Temp qw(tempdir);
use FindBin;
use IPC::Cmd qw(run);
use JSON::PP qw(decode_json);

use lib File::Spec->catdir($FindBin::Bin, '..', 'perl');

use FSM::Adapter::IAL2::PPIF;

subtest 'adapter accepts the selected AHB byte-lane subordinate .ahb profile alias' => sub {
    ok(-f sample_byte_lane_alias_path(), 'tracked runnable AHB byte-lane subordinate .ahb alias sample exists');

    my $alias = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_byte_lane_alias_path());
    my $ppif = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_byte_lane_ppif_path());

    is($alias->{layer}, 'IAL2', 'AHB byte-lane subordinate .ahb parser result stays IAL2');
    is($alias->{kind}, 'protocol_intent.ahb_subordinate', 'AHB byte-lane subordinate .ahb parser result keeps subordinate kind');
    is($alias->{mode}, 'subordinate', 'AHB byte-lane subordinate .ahb parser result keeps subordinate mode');
    is($alias->{generated_ial1}{name}, 'ahb_lite_subordinate_byte_lane.isf', '.ahb exposes generated byte-lane IAL1 artifact');
    is($alias->{generated_ial1}{text}, $ppif->{generated_ial1}{text}, '.ahb mirrors byte-lane .ppif generated IAL1 text');
    is_deeply($alias->{generated_ial0}{files}, $ppif->{generated_ial0}{files}, '.ahb mirrors byte-lane .ppif generated IAL0 files');
    is($alias->{report}{schema}, 'fsmgen.ial2.protocol_intent.ahb_subordinate.v1', '.ahb report keeps the AHB subordinate schema');
    is($alias->{report}{source_object}{id}, 'fsmgen-ahb-lite-subordinate-byte-lane', '.ahb preserves byte-lane subordinate source object id');
    is($alias->{report}{source_object}{intent_name}, 'ahb_lite_subordinate_byte_lane', '.ahb preserves byte-lane subordinate intent name');
    is($alias->{report}{target_protocol}{profile}, 'ahb', '.ahb preserves explicit AHB profile');
    is($alias->{report}{target_protocol}{object}, 'ahb-subordinate', '.ahb preserves AHB subordinate object');
    is($alias->{report}{target_protocol}{role}, 'subordinate', '.ahb preserves AHB subordinate role');
    is($alias->{report}{target_protocol}{transfer}, 'ahb_lite_byte_lane_access', '.ahb preserves selected byte-lane transfer');
    is($alias->{report}{layering}{direct_ial2_to_ial0}, 0, '.ahb keeps direct IAL2-to-IAL0 lowering forbidden');
    is_deeply($alias->{report}{transfer}{supported_size}, [qw(byte halfword word)], '.ahb report preserves byte/halfword/word supported sizes');
    is($alias->{report}{transfer}{narrow_write}, 'preserve-inactive-lanes', '.ahb report preserves narrow-write policy');
    is($alias->{report}{transfer}{narrow_read}, 'zero-fill-inactive-lanes', '.ahb report preserves narrow-read policy');
    is($alias->{report}{narrow_transfer_policy}{supported_sizes}[0]{hsize}, "3'b000", '.ahb report preserves byte HSIZE policy');
    is($alias->{report}{narrow_transfer_policy}{byte_lanes}[3]{mask}, "32'hff000000", '.ahb report preserves lane mask policy');
    is($alias->{report}{generated_artifacts}{ial1}{name}, 'ahb_lite_subordinate_byte_lane.isf', '.ahb report names generated IAL1 before IAL0');
    is_deeply($alias->{report}{generated_artifacts}{ial0}{files}, ['ahb_lite_subordinate_byte_lane.fsm'], '.ahb report names generated IAL0 artifact');
    is($alias->{report}{generated_artifacts}{hdl_entry}{entry_artifact}, 'ahb_lite_subordinate_byte_lane.fsm', '.ahb report selects generated byte-lane .fsm as HDL entry');

    my %alias_residue = map { $_->{id} => 1 } @{$alias->{report}{unsupported_residue}};
    ok(!$alias_residue{ahb_subordinate_profile_alias_deferred}, '.ahb report removes stale subordinate profile-alias residue');
    ok($alias_residue{ahb_interconnect_generation_deferred}, '.ahb report keeps interconnect/decode residue explicit');
    ok($alias_residue{ahb_subordinate_optional_signal_residue}, '.ahb report keeps optional-signal residue explicit');
    ok($alias_residue{ahb_burst_seq_support_deferred}, '.ahb report keeps burst SEQ residue explicit');
    ok($alias_residue{ahb_verification_output_deferred}, '.ahb report keeps verification/backend residue explicit');

    my %ppif_residue = map { $_->{id} => 1 } @{$ppif->{report}{unsupported_residue}};
    ok($ppif_residue{ahb_subordinate_profile_alias_deferred}, 'generic byte-lane PPIF report preserves alias-deferred residue');
};

subtest 'byte-lane subordinate .ahb diagnostics stay fail-closed for malformed aliases' => sub {
    my $tempdir = tempdir(CLEANUP => 1);

    my $missing_profile_path = File::Spec->catfile($tempdir, 'missing_profile.ahb');
    my $missing_profile_source = sample_byte_lane_alias_source();
    $missing_profile_source =~ s/^\s*\(profile ahb\)\n//m;
    write_file($missing_profile_path, $missing_profile_source);
    my $missing_ok = eval { FSM::Adapter::IAL2::PPIF->new()->parse_file($missing_profile_path); 1 };
    ok(!$missing_ok, 'byte-lane .ahb without explicit profile is rejected');
    like(
        $@,
        qr/\.ahb source '.*missing_profile\.ahb' is missing required \(profile \.\.\.\) clause/,
        'byte-lane .ahb missing-profile diagnostic is targeted',
    );

    my $mismatch_path = File::Spec->catfile($tempdir, 'valid_ready_profile.ahb');
    write_file($mismatch_path, slurp(sample_valid_ready_handshake_ppif_path()));
    my $mismatch_ok = eval { FSM::Adapter::IAL2::PPIF->new()->parse_file($mismatch_path); 1 };
    ok(!$mismatch_ok, 'byte-lane .ahb with a non-AHB profile is rejected');
    like(
        $@,
        qr/profile 'valid-ready' does not match \.ahb profile alias; expected ahb/,
        'byte-lane .ahb suffix/profile mismatch diagnostic is targeted',
    );

    my @cases = (
        [
            'missing supported halfword',
            sub {
                my $source = sample_byte_lane_alias_source();
                $source =~ s/\n      \(supported-size halfword\)//;
                return $source;
            },
            qr/transfer\.supported_size must contain exactly byte, halfword, and word/,
        ],
        [
            'duplicate supported byte',
            sub {
                my $source = sample_byte_lane_alias_source();
                $source =~ s/\(supported-size halfword\)/(supported-size byte)/;
                return $source;
            },
            qr/transfer\.supported_size has duplicate 'byte'/,
        ],
        [
            'unsupported lane order',
            sub {
                my $source = sample_byte_lane_alias_source();
                $source =~ s/\(lane-order little-endian\)/(lane-order big-endian)/;
                return $source;
            },
            qr/transfer\.lane_order must be little-endian/,
        ],
        [
            'duplicate subordinate object',
            sub {
                my $source = sample_byte_lane_alias_source();
                my $object = sample_byte_lane_subordinate_object();
                $object =~ s/\(ahb-subordinate ahb_lite_subordinate_byte_lane\b/(ahb-subordinate ahb_lite_subordinate_byte_lane_shadow/;
                $source =~ s/\)\s*\z/  $object\)\n/s;
                return $source;
            },
            qr/supports exactly one \(ahb-subordinate \.\.\.\) object in this slice/,
        ],
    );

    for my $case (@cases) {
        my ($label, $build_source, $pattern) = @$case;
        my $path = File::Spec->catfile($tempdir, "$label.ahb");
        write_file($path, $build_source->());
        my $ok = eval { FSM::Adapter::IAL2::PPIF->new()->parse_file($path); 1 };
        ok(!$ok, "$label is rejected");
        like($@, $pattern, "$label diagnostic is targeted");
    }
};

subtest 'CLI JSON surfaces report byte-lane subordinate .ahb source identity and support accounting' => sub {
    my $check = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--check', '--json', sample_byte_lane_alias_path());
    ok($check->{success}, '--check --json succeeds for byte-lane subordinate .ahb');
    is(
        $check->{source}{resolved_path},
        File::Spec->rel2abs(sample_byte_lane_alias_path()),
        'byte-lane subordinate .ahb check JSON reports the public alias source path',
    );
    is($check->{result}{module_name}, 'ahb_lite_subordinate_byte_lane', 'byte-lane subordinate .ahb check JSON reports generated module name');
    is($check->{support_accounting}{entry_id}, 'intent.ahb_profile_alias_subordinate_byte_lane', 'byte-lane subordinate .ahb support accounting names the profile-alias corpus entry');
    is($check->{support_accounting}{source_kind}, 'ial2_profile_alias', 'byte-lane subordinate .ahb records profile-alias source kind');
    is($check->{support_accounting}{coverage}, 'ial2_ahb_profile_alias_subordinate_byte_lane_pipeline_cli', 'byte-lane subordinate .ahb records selected coverage key');

    my $semantic = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--emit-semantic-json', sample_byte_lane_alias_path());
    ok($semantic->{success}, '--emit-semantic-json succeeds for byte-lane subordinate .ahb');
    is(
        $semantic->{source}{resolved_path},
        File::Spec->rel2abs(sample_byte_lane_alias_path()),
        'byte-lane subordinate .ahb semantic JSON reports the public alias source path',
    );
    is($semantic->{generation_result_snapshot}{summary}{module_name}, 'ahb_lite_subordinate_byte_lane', 'byte-lane subordinate .ahb semantic JSON reports generated module name');
    is($semantic->{generation_result_snapshot}{summary}{source_root_kind}, 'fsm', 'byte-lane subordinate .ahb semantic JSON reports generated FSM source root');
    is($semantic->{support_accounting}{entry_id}, 'intent.ahb_profile_alias_subordinate_byte_lane', 'byte-lane subordinate .ahb semantic JSON support accounting names the profile-alias corpus entry');
    is($semantic->{support_accounting}{source_kind}, 'ial2_profile_alias', 'byte-lane subordinate .ahb semantic JSON records profile-alias source kind');
};

subtest 'schedule JSON and outdir expose byte-lane subordinate .ahb review artifacts' => sub {
    my $schedule = run_json_command('./bin/fsmgen', '--quiet', '--emit-schedule-json', sample_byte_lane_alias_path());
    is($schedule->{schema}, 'fsmgen.ial2.protocol_intent.ahb_subordinate.v1', 'byte-lane subordinate .ahb schedule JSON reports the AHB subordinate schema');
    is($schedule->{target_protocol}{profile}, 'ahb', 'byte-lane subordinate .ahb schedule JSON reports the AHB profile');
    is($schedule->{target_protocol}{object}, 'ahb-subordinate', 'byte-lane subordinate .ahb schedule JSON reports the AHB subordinate object');
    is($schedule->{generated_artifacts}{ial1}{name}, 'ahb_lite_subordinate_byte_lane.isf', 'byte-lane subordinate .ahb schedule JSON exposes generated IAL1 artifact');
    is_deeply($schedule->{generated_artifacts}{ial0}{files}, ['ahb_lite_subordinate_byte_lane.fsm'], 'byte-lane subordinate .ahb schedule JSON exposes generated IAL0 artifact');
    is_deeply($schedule->{transfer}{supported_size}, [qw(byte halfword word)], 'byte-lane subordinate .ahb schedule JSON exposes supported sizes');
    is($schedule->{narrow_transfer_policy}{narrow_read}{policy}, 'zero-fill-inactive-lanes', 'byte-lane subordinate .ahb schedule JSON exposes narrow-read policy');
    my %schedule_residue = map { $_->{id} => 1 } @{$schedule->{unsupported_residue}};
    ok(!$schedule_residue{ahb_subordinate_profile_alias_deferred}, 'byte-lane subordinate .ahb schedule JSON removes stale profile-alias residue');
    ok($schedule_residue{ahb_interconnect_generation_deferred}, 'byte-lane subordinate .ahb schedule JSON keeps interconnect residue');

    my $tempdir = tempdir(CLEANUP => 1);
    my $outdir = File::Spec->catdir($tempdir, 'out');
    my $hdl = File::Spec->catfile($tempdir, 'ahb_lite_subordinate_byte_lane.sv');
    my ($success, undef, undef, undef, $stderr) = run(
        command => ['./bin/fsmgen', '--quiet', '--outdir', $outdir, '--output', $hdl, sample_byte_lane_alias_path()],
    );
    ok($success, 'byte-lane subordinate .ahb emits HDL and review artifacts through --outdir');
    is(join('', @{$stderr || []}), '', 'byte-lane subordinate .ahb outdir generation keeps stderr clean');
    ok(-f File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane.isf'), 'outdir contains generated byte-lane IAL1 artifact');
    ok(-f File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane.fsm'), 'outdir contains generated byte-lane IAL0 artifact');
    ok(-f $hdl, 'outdir command emits selected byte-lane subordinate HDL output');
    like(slurp(File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane.isf')), qr/32'h000000ff/, 'outdir generated .isf keeps byte-lane mask');
    like(slurp(File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane.fsm')), qr/read_halfword_lane1_hit_start/, 'outdir generated .fsm keeps halfword read lane drive');
    like(slurp($hdl), qr/\bmodule\s+ahb_lite_subordinate_byte_lane\b/, 'generated HDL contains byte-lane AHB subordinate module');
};

subtest 'existing generic byte-lane and word-only subordinate surfaces stay unchanged' => sub {
    my $ppif = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_byte_lane_ppif_path());
    my %ppif_residue = map { $_->{id} => 1 } @{$ppif->{report}{unsupported_residue}};
    ok($ppif_residue{ahb_subordinate_profile_alias_deferred}, 'generic byte-lane PPIF still keeps .ahb alias residue explicit');
    is_deeply($ppif->{report}{transfer}{supported_size}, [qw(byte halfword word)], 'generic byte-lane PPIF keeps supported-size policy');
    is($ppif->{report}{narrow_transfer_policy}{narrow_write}{policy}, 'preserve-inactive-lanes', 'generic byte-lane PPIF keeps narrow-write policy');

    my $word_alias = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--check', '--json', sample_word_only_alias_path());
    ok($word_alias->{success}, 'existing word-only subordinate .ahb alias still checks successfully');
    is($word_alias->{result}{module_name}, 'ahb_lite_subordinate', 'existing word-only subordinate .ahb alias keeps module name');
    is($word_alias->{support_accounting}{entry_id}, 'intent.ahb_profile_alias_subordinate', 'existing word-only subordinate .ahb alias keeps support identity');
    is($word_alias->{support_accounting}{coverage}, 'ial2_ahb_profile_alias_subordinate_pipeline_cli', 'existing word-only subordinate .ahb alias keeps coverage key');

    my $word_ppif = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_word_only_ppif_path());
    ok(!exists $word_ppif->{report}{narrow_transfer_policy}, 'word-only PPIF still does not gain a narrow-transfer policy block');
    unlike($word_ppif->{generated_ial1}{text}, qr/read_byte_lane/, 'word-only PPIF does not gain byte-lane read drives');
};

done_testing();

sub sample_byte_lane_ppif_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate_byte_lane.ppif');
}

sub sample_byte_lane_alias_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate_byte_lane.ahb');
}

sub sample_word_only_ppif_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate.ppif');
}

sub sample_word_only_alias_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate.ahb');
}

sub sample_valid_ready_handshake_ppif_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'valid_ready_handshake.ppif');
}

sub sample_byte_lane_alias_source {
    return slurp(sample_byte_lane_alias_path());
}

sub sample_byte_lane_subordinate_object {
    my $source = sample_byte_lane_alias_source();
    $source =~ /(\n  \(ahb-subordinate\b.*)\)\s*\z/s
        or die 'Cannot extract AHB byte-lane subordinate object';
    return $1;
}

sub run_json_command {
    my @command = @_;
    my ($success, undef, undef, $stdout, $stderr) = run(command => \@command);
    my $json = join('', @{$stdout || []});
    my $decoded = eval { decode_json($json) };
    ok($decoded, join(' ', @command) . ' emits decodable JSON')
        or do {
            diag($json);
            diag(join('', @{$stderr || []}));
            diag('command failed') unless $success;
            return {};
        };
    return $decoded;
}

sub write_file {
    my ($path, $text) = @_;
    open my $fh, '>', $path or die "write $path: $!";
    print {$fh} $text;
    close $fh or die "close $path: $!";
}

sub slurp {
    my ($path) = @_;
    open my $fh, '<', $path or die "Cannot read $path: $!";
    local $/;
    return <$fh>;
}
