#!/usr/bin/env perl
use strict;
use warnings;
use Test::More;
use File::Spec;
use File::Temp qw(tempdir);
use FindBin;
use IPC::Cmd qw(run);
use JSON::PP qw(decode_json);

use lib File::Spec->catdir($FindBin::Bin, '..', 'perl');

use FSM::Adapter::IAL2::PPIF;

subtest 'adapter parses selected AHB subordinate byte-lane SEQ PPIF shape' => sub {
    ok(-f sample_seq_ppif_path(), 'tracked runnable AHB byte-lane SEQ subordinate PPIF sample exists');
    like(sample_seq_ppif(), qr/\(seq-policy in-word-progressive\)/, 'sample carries the selected in-word SEQ policy clause');

    my $result = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_seq_ppif_path());

    is($result->{layer}, 'IAL2', 'AHB byte-lane SEQ subordinate adapter result stays IAL2');
    is($result->{kind}, 'protocol_intent.ahb_subordinate', 'adapter returns the AHB subordinate kind');
    is($result->{mode}, 'subordinate', 'AHB byte-lane SEQ subordinate mode is explicit');
    is($result->{report}{source_object}{id}, 'fsmgen-ahb-lite-subordinate-byte-lane-seq', 'source object id is preserved');
    is($result->{report}{source_object}{intent_name}, 'ahb_lite_subordinate_byte_lane_seq', 'source intent name is preserved');
    is($result->{report}{target_protocol}{transfer}, 'ahb_lite_byte_lane_seq_access', 'report names selected transfer');

    my $isf = $result->{generated_ial1}{text};
    is($result->{generated_ial1}{name}, 'ahb_lite_subordinate_byte_lane_seq.isf', 'generated IAL1 artifact is named');
    like($isf, qr/\A\(actor ahb_lite_subordinate_byte_lane_seq\b/, 'generated IAL1 names byte-lane SEQ subordinate actor');
    like($isf, qr/\(var seq_valid_q \(width 1\) \(reset 0\)\)/, 'generated IAL1 stores whether SEQ continuation is armed');
    like($isf, qr/\(var seq_expected_addr_q \(width 32\) \(reset 0\)\)/, 'generated IAL1 stores the expected next in-word address');
    like($isf, qr/\(var seq_size_q \(width 3\) \(reset 0\)\)/, 'generated IAL1 stores the prior HSIZE for SEQ control stability');
    like($isf, qr/\(var seq_write_q \(width 1\) \(reset 0\)\)/, 'generated IAL1 stores the prior HWRITE for SEQ control stability');
    like($isf, qr/\(transaction ahb_seq_idle_clear\s+\(when \(& HSEL HREADY \(\| \(== HTRANS 2'b00\) \(== HTRANS 2'b01\)\)\)/s, 'generated IAL1 clears continuation history on accepted IDLE/BUSY');
    like($isf, qr/\(when \(& HSEL HREADY \(\| \(== HTRANS 2'b10\) \(== HTRANS 2'b11\)\)\)/, 'generated IAL1 admits active NONSEQ/SEQ transfer phases');
    unlike($isf, qr/\(when \(== trans_q 2'b11\)\s+\(drive error_first\)\s+\(drive error_complete\)\)/s, 'generated IAL1 does not keep the unconditional SEQ error path');
    like($isf, qr/\(when \(& \(== trans_q 2'b11\) \(! \(& \(& seq_valid_q \(== addr_q seq_expected_addr_q\) \(== size_q seq_size_q\) \(== write_q seq_write_q\)\)/, 'generated IAL1 rejects standalone or mismatched SEQ transfers');
    like($isf, qr/\(when \(& \(== trans_q 2'b10\).*32'h00000000.*write_q\)\s+\(set reg_data_q.*32'h000000ff.*\)\s+\(set seq_valid_q 1\)\s+\(set seq_expected_addr_q 32'h00000001\)/s, 'NONSEQ byte lane 0 arms byte SEQ address 1');
    like($isf, qr/\(when \(& \(== trans_q 2'b11\).*seq_expected_addr_q.*32'h00000001.*write_q\)\s+\(set reg_data_q.*32'h0000ff00.*\)\s+\(set seq_valid_q 1\)\s+\(set seq_expected_addr_q 32'h00000002\)/s, 'SEQ byte lane 1 accepts the expected address and arms byte SEQ address 2');
    like($isf, qr/\(when \(& \(== trans_q 2'b11\).*32'h00000003.*write_q\)\s+\(set reg_data_q.*32'hff000000.*\)\s+\(set seq_valid_q 0\)/s, 'SEQ byte lane 3 completes in-word progression and clears continuation history');
    like($isf, qr/\(when \(& \(== trans_q 2'b10\).*size_q 1.*32'h00000000.*write_q\)\s+\(set reg_data_q.*32'h0000ffff.*\)\s+\(set seq_valid_q 1\)\s+\(set seq_expected_addr_q 32'h00000002\)/s, 'NONSEQ halfword lane 0 arms halfword SEQ address 2');
    like($isf, qr/\(when \(& \(== trans_q 2'b11\).*size_q 1.*32'h00000002.*write_q\)\s+\(set reg_data_q.*32'hffff0000.*\)\s+\(set seq_valid_q 0\)/s, 'SEQ halfword lane 1 completes in-word progression and clears continuation history');
    like($isf, qr/\(when \(& \(== trans_q 2'b10\).*size_q 2.*write_q\)\s+\(set reg_data_q HWDATA\)\s+\(set seq_valid_q 0\)/s, 'NONSEQ word access remains supported but does not arm SEQ continuation');

    is_deeply(
        sorted([keys %{$result->{generated_ial0}{files}}]),
        ['ahb_lite_subordinate_byte_lane_seq.fsm'],
        'adapter exposes generated byte-lane SEQ AHB IAL0 .fsm file map',
    );
    my $fsm = $result->{generated_ial0}{files}{'ahb_lite_subordinate_byte_lane_seq.fsm'};
    like($fsm, qr/\(\?fsm:ahb_lite_subordinate_byte_lane_seq\b/, 'generated IAL0 names byte-lane SEQ subordinate FSM');
    like($fsm, qr/seq_valid_q/, 'generated IAL0 carries continuation-valid state');
    like($fsm, qr/seq_expected_addr_q/, 'generated IAL0 carries expected-address state');
    like($fsm, qr/read_halfword_lane1_hit_start/, 'generated IAL0 carries terminal halfword read lane drive');

    is_deeply($result->{report}{transfer}{supported_size}, [qw(byte halfword word)], 'report keeps selected byte-lane supported sizes');
    is($result->{report}{transfer}{seq_policy}{mode}, 'in_word_progressive', 'report captures selected SEQ policy mode');
    is($result->{report}{transfer}{seq_policy}{requires_prior_transfer}, 'prior_okay_nonseq_or_seq', 'report captures prior-transfer requirement');
    is_deeply($result->{report}{transfer}{seq_policy}{supported_sizes}, [qw(byte halfword)], 'report narrows SEQ policy to byte/halfword');
    is($result->{report}{transfer}{seq_policy}{address_progression}, 'previous_address_plus_size_bytes', 'report captures address progression');
    is_deeply($result->{report}{transfer}{seq_policy}{control_stability}, [qw(HWRITE HSIZE)], 'report captures required stable control fields');
    is_deeply($result->{report}{transfer}{seq_policy}{clears_on}, [qw(reset idle busy error new_nonseq)], 'report captures continuation-history clear events');
    is($result->{report}{narrow_transfer_policy}{byte_lanes}[2]{mask}, "32'h00ff0000", 'report keeps byte-lane policy alongside SEQ policy');
    is($result->{report}{generated_artifacts}{hdl_entry}{entry_artifact}, 'ahb_lite_subordinate_byte_lane_seq.fsm', 'report selects generated byte-lane SEQ subordinate .fsm as HDL entry');

    my %residue = map { $_->{id} => $_->{detail} } @{$result->{report}{unsupported_residue}};
    ok($residue{ahb_subordinate_profile_alias_deferred}, 'report keeps .ahb alias residue explicit for the new generic source');
    like($residue{ahb_burst_seq_support_deferred}, qr/HBURST-driven length\/wrap semantics/, 'report narrows remaining SEQ residue to HBURST-driven burst work');
    like($residue{ahb_burst_seq_support_deferred}, qr/\.ahb alias exposure, aggregate propagation/, 'report keeps alias and aggregate SEQ propagation deferred');
};

subtest 'malformed byte-lane SEQ AHB subordinate PPIF sources fail closed' => sub {
    my @cases = (
        [
            'duplicate seq policy',
            sub {
                my $source = sample_seq_ppif();
                $source =~ s/\(seq-policy in-word-progressive\)/(seq-policy in-word-progressive)\n      (seq-policy in-word-progressive)/;
                return $source;
            },
            qr/duplicate \(seq-policy \.\.\.\) clause/,
        ],
        [
            'unsupported seq policy',
            sub {
                my $source = sample_seq_ppif();
                $source =~ s/\(seq-policy in-word-progressive\)/(seq-policy full-burst)/;
                return $source;
            },
            qr/transfer\.seq_policy must be in-word-progressive or hburst-in-word-progressive/,
        ],
        [
            'seq policy without byte-lane size policy',
            sub {
                my $source = sample_seq_ppif();
                $source =~ s/\n      \(supported-size (?:byte|halfword|word)\)//g;
                $source =~ s/\n      \((?:lane-order|narrow-write|narrow-read|unaligned-access|crossing-access) [^)]+\)//g;
                return $source;
            },
            qr/transfer\.seq_policy requires the selected byte-lane size policy/,
        ],
        [
            'seq policy cannot widen supported-transfer scalar',
            sub {
                my $source = sample_seq_ppif();
                $source =~ s/\(supported-transfer nonseq\)/(supported-transfer seq)/;
                return $source;
            },
            qr/transfer\.supported_transfer must be nonseq/,
        ],
    );

    for my $case (@cases) {
        my ($label, $build_source, $pattern) = @$case;
        my $ok = eval {
            FSM::Adapter::IAL2::PPIF->new()->parse_source($build_source->(), "$label.ppif");
            1;
        };
        ok(!$ok, "$label is rejected");
        like($@, $pattern, "$label diagnostic is targeted");
    }
};

subtest 'CLI checks, semantic export, schedule report, and outdir use the byte-lane SEQ path' => sub {
    my $check = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--check', '--json', sample_seq_ppif_path());
    ok($check->{success}, 'strict check JSON succeeds for byte-lane SEQ AHB subordinate PPIF');
    is($check->{result}{module_name}, 'ahb_lite_subordinate_byte_lane_seq', 'check JSON reports generated byte-lane SEQ subordinate module name');
    is($check->{support_accounting}{entry_id}, 'intent.ppif_ahb_lite_subordinate_byte_lane_seq', 'check JSON matches byte-lane SEQ support accounting');
    is($check->{support_accounting}{source_kind}, 'ppif', 'check JSON reports PPIF source kind');
    is($check->{support_accounting}{coverage}, 'ial2_ppif_ahb_lite_subordinate_byte_lane_seq_pipeline_cli', 'check JSON reports selected coverage key');

    my $semantic = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--emit-semantic-json', sample_seq_ppif_path());
    ok($semantic->{success}, 'strict semantic JSON succeeds for byte-lane SEQ AHB subordinate PPIF');
    is($semantic->{generation_result_snapshot}{summary}{module_name}, 'ahb_lite_subordinate_byte_lane_seq', 'semantic JSON reports generated module name');
    is($semantic->{support_accounting}{entry_id}, 'intent.ppif_ahb_lite_subordinate_byte_lane_seq', 'semantic JSON matches byte-lane SEQ support accounting');

    my $schedule = run_json_command('./bin/fsmgen', '--quiet', '--emit-schedule-json', sample_seq_ppif_path());
    is($schedule->{schema}, 'fsmgen.ial2.protocol_intent.ahb_subordinate.v1', 'schedule/report JSON exposes AHB subordinate schema');
    is($schedule->{generated_artifacts}{ial1}{name}, 'ahb_lite_subordinate_byte_lane_seq.isf', 'schedule/report JSON exposes generated IAL1 artifact');
    is_deeply($schedule->{generated_artifacts}{ial0}{files}, ['ahb_lite_subordinate_byte_lane_seq.fsm'], 'schedule/report JSON exposes generated IAL0 artifact');
    is($schedule->{transfer}{seq_policy}{mode}, 'in_word_progressive', 'schedule/report JSON exposes selected SEQ policy mode');
    is_deeply($schedule->{transfer}{seq_policy}{supported_sizes}, [qw(byte halfword)], 'schedule/report JSON exposes selected SEQ continuation sizes');

    my $tempdir = tempdir(CLEANUP => 1);
    my $outdir = File::Spec->catdir($tempdir, 'out');
    my $hdl = File::Spec->catfile($tempdir, 'ahb_lite_subordinate_byte_lane_seq.sv');
    my ($success, undef, undef, undef, $stderr) = run(
        command => ['./bin/fsmgen', '--quiet', '--outdir', $outdir, '--output', $hdl, sample_seq_ppif_path()],
    );
    ok($success, 'byte-lane SEQ AHB subordinate PPIF emits HDL and review artifacts through --outdir');
    is(join('', @{$stderr || []}), '', 'outdir generation keeps stderr clean');
    ok(-f File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane_seq.isf'), 'outdir contains generated byte-lane SEQ IAL1 artifact');
    ok(-f File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane_seq.fsm'), 'outdir contains generated byte-lane SEQ IAL0 artifact');
    ok(-f $hdl, 'outdir command emits selected byte-lane SEQ subordinate HDL output');
    like(slurp(File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane_seq.isf')), qr/seq_expected_addr_q/, 'outdir generated .isf keeps expected-address state');
    like(slurp(File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane_seq.fsm')), qr/seq_write_q/, 'outdir generated .fsm keeps write-control stability state');
    like(slurp($hdl), qr/\bmodule\s+ahb_lite_subordinate_byte_lane_seq\b/, 'generated HDL contains byte-lane SEQ AHB subordinate module');
};

subtest 'existing AHB subordinate sources and aliases stay unchanged at the public boundary' => sub {
    my $byte_lane = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_byte_lane_ppif_path());
    ok(!exists $byte_lane->{report}{transfer}{seq_policy}, 'existing byte-lane PPIF report does not gain SEQ policy');
    like($byte_lane->{generated_ial1}{text}, qr/\(when \(== trans_q 2'b11\)\s+\(drive error_first\)\s+\(drive error_complete\)\)/s, 'existing byte-lane PPIF still rejects SEQ unconditionally');

    my $word_only = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_word_only_ppif_path());
    ok(!exists $word_only->{report}{transfer}{seq_policy}, 'word-only PPIF report does not gain SEQ policy');
    ok(!exists $word_only->{report}{narrow_transfer_policy}, 'word-only PPIF report remains word-only');

    my $alias_check = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--check', '--json', sample_byte_lane_alias_path());
    ok($alias_check->{success}, 'existing byte-lane subordinate .ahb alias still checks successfully');
    is($alias_check->{result}{module_name}, 'ahb_lite_subordinate_byte_lane', 'existing byte-lane subordinate .ahb alias keeps module name');
    is($alias_check->{support_accounting}{entry_id}, 'intent.ahb_profile_alias_subordinate_byte_lane', 'existing byte-lane subordinate .ahb alias keeps support identity');
    is($alias_check->{support_accounting}{coverage}, 'ial2_ahb_profile_alias_subordinate_byte_lane_pipeline_cli', 'existing byte-lane subordinate .ahb alias keeps coverage key');
};

done_testing();

sub sample_seq_ppif_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate_byte_lane_seq.ppif');
}

sub sample_byte_lane_ppif_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate_byte_lane.ppif');
}

sub sample_word_only_ppif_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate.ppif');
}

sub sample_byte_lane_alias_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate_byte_lane.ahb');
}

sub sample_seq_ppif {
    return slurp(sample_seq_ppif_path());
}

sub run_json_command {
    my @command = @_;
    my ($success, undef, undef, $stdout, $stderr) = run(command => \@command);
    my $json = join('', @{$stdout || []});
    my $decoded = eval { decode_json($json) };
    ok($decoded, join(' ', @command) . ' emits decodable JSON')
        or do {
            diag($json);
            diag(join('', @{$stderr || []}));
            diag('command failed') unless $success;
            return {};
        };
    return $decoded;
}

sub slurp {
    my ($path) = @_;
    open my $fh, '<', $path or die "Cannot read $path: $!";
    local $/;
    return <$fh>;
}

sub sorted {
    my ($values) = @_;
    return [sort @$values];
}
