#!/usr/bin/env perl
use strict;
use warnings;
use Test::More;
use File::Spec;
use File::Temp qw(tempdir);
use FindBin;
use IPC::Cmd qw(run);
use JSON::PP qw(decode_json);

use lib File::Spec->catdir($FindBin::Bin, '..', 'perl');

use FSM::Adapter::IAL2::PPIF;

subtest 'adapter accepts the selected AHB byte-lane SEQ subordinate .ahb profile alias' => sub {
    ok(-f sample_seq_alias_path(), 'tracked runnable AHB byte-lane SEQ subordinate .ahb alias sample exists');

    my $alias = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_seq_alias_path());
    my $ppif = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_seq_ppif_path());

    is($alias->{layer}, 'IAL2', 'AHB byte-lane SEQ .ahb parser result stays IAL2');
    is($alias->{kind}, 'protocol_intent.ahb_subordinate', 'AHB byte-lane SEQ .ahb parser result keeps subordinate kind');
    is($alias->{mode}, 'subordinate', 'AHB byte-lane SEQ .ahb parser result keeps subordinate mode');
    is($alias->{generated_ial1}{name}, 'ahb_lite_subordinate_byte_lane_seq.isf', '.ahb exposes generated byte-lane SEQ IAL1 artifact');
    is($alias->{generated_ial1}{text}, $ppif->{generated_ial1}{text}, '.ahb mirrors byte-lane SEQ .ppif generated IAL1 text');
    is_deeply($alias->{generated_ial0}{files}, $ppif->{generated_ial0}{files}, '.ahb mirrors byte-lane SEQ .ppif generated IAL0 files');
    is($alias->{report}{schema}, 'fsmgen.ial2.protocol_intent.ahb_subordinate.v1', '.ahb report keeps the AHB subordinate schema');
    is($alias->{report}{source_object}{id}, 'fsmgen-ahb-lite-subordinate-byte-lane-seq', '.ahb preserves byte-lane SEQ source object id');
    is($alias->{report}{source_object}{intent_name}, 'ahb_lite_subordinate_byte_lane_seq', '.ahb preserves byte-lane SEQ intent name');
    is($alias->{report}{target_protocol}{profile}, 'ahb', '.ahb preserves explicit AHB profile');
    is($alias->{report}{target_protocol}{object}, 'ahb-subordinate', '.ahb preserves AHB subordinate object');
    is($alias->{report}{target_protocol}{transfer}, 'ahb_lite_byte_lane_seq_access', '.ahb preserves selected byte-lane SEQ transfer');
    is($alias->{report}{layering}{direct_ial2_to_ial0}, 0, '.ahb keeps direct IAL2-to-IAL0 lowering forbidden');
    is_deeply($alias->{report}{transfer}{supported_size}, [qw(byte halfword word)], '.ahb report preserves byte/halfword/word supported sizes');
    is($alias->{report}{transfer}{seq_policy}{mode}, 'in_word_progressive', '.ahb report preserves selected SEQ policy');
    is_deeply($alias->{report}{transfer}{seq_policy}{supported_sizes}, [qw(byte halfword)], '.ahb report preserves SEQ supported sizes');
    is($alias->{report}{narrow_transfer_policy}{byte_lanes}[3]{mask}, "32'hff000000", '.ahb report preserves byte-lane mask policy');
    is($alias->{report}{generated_artifacts}{ial1}{name}, 'ahb_lite_subordinate_byte_lane_seq.isf', '.ahb report names generated IAL1 before IAL0');
    is_deeply($alias->{report}{generated_artifacts}{ial0}{files}, ['ahb_lite_subordinate_byte_lane_seq.fsm'], '.ahb report names generated IAL0 artifact');
    is($alias->{report}{generated_artifacts}{hdl_entry}{entry_artifact}, 'ahb_lite_subordinate_byte_lane_seq.fsm', '.ahb report selects generated byte-lane SEQ .fsm as HDL entry');

    my %alias_residue = map { $_->{id} => $_->{detail} } @{$alias->{report}{unsupported_residue}};
    ok(!exists $alias_residue{ahb_subordinate_profile_alias_deferred}, '.ahb report removes stale subordinate profile-alias residue');
    ok($alias_residue{ahb_burst_seq_support_deferred}, '.ahb report keeps remaining SEQ residue explicit');
    unlike($alias_residue{ahb_burst_seq_support_deferred}, qr/\.ahb alias exposure/, '.ahb report no longer says alias exposure is deferred');
    like($alias_residue{ahb_burst_seq_support_deferred}, qr/aggregate propagation/, '.ahb report keeps aggregate SEQ propagation deferred');
    like($alias_residue{ahb_burst_seq_support_deferred}, qr/HBURST-driven length\/wrap semantics/, '.ahb report keeps HBURST length/wrap residue');

    my %ppif_residue = map { $_->{id} => $_->{detail} } @{$ppif->{report}{unsupported_residue}};
    ok($ppif_residue{ahb_subordinate_profile_alias_deferred}, 'generic byte-lane SEQ PPIF report preserves alias-deferred residue');
    like($ppif_residue{ahb_burst_seq_support_deferred}, qr/\.ahb alias exposure/, 'generic byte-lane SEQ PPIF report keeps alias exposure deferred');
};

subtest 'byte-lane SEQ subordinate .ahb diagnostics stay fail-closed for malformed aliases' => sub {
    my $tempdir = tempdir(CLEANUP => 1);

    my $missing_profile_path = File::Spec->catfile($tempdir, 'missing_profile.ahb');
    my $missing_profile_source = sample_seq_alias_source();
    $missing_profile_source =~ s/^\s*\(profile ahb\)\n//m;
    write_file($missing_profile_path, $missing_profile_source);
    my $missing_ok = eval { FSM::Adapter::IAL2::PPIF->new()->parse_file($missing_profile_path); 1 };
    ok(!$missing_ok, 'byte-lane SEQ .ahb without explicit profile is rejected');
    like(
        $@,
        qr/\.ahb source '.*missing_profile\.ahb' is missing required \(profile \.\.\.\) clause/,
        'byte-lane SEQ .ahb missing-profile diagnostic is targeted',
    );

    my $mismatch_path = File::Spec->catfile($tempdir, 'valid_ready_profile.ahb');
    write_file($mismatch_path, slurp(sample_valid_ready_handshake_ppif_path()));
    my $mismatch_ok = eval { FSM::Adapter::IAL2::PPIF->new()->parse_file($mismatch_path); 1 };
    ok(!$mismatch_ok, 'byte-lane SEQ .ahb with a non-AHB profile is rejected');
    like(
        $@,
        qr/profile 'valid-ready' does not match \.ahb profile alias; expected ahb/,
        'byte-lane SEQ .ahb suffix/profile mismatch diagnostic is targeted',
    );

    my @cases = (
        [
            'duplicate seq policy',
            sub {
                my $source = sample_seq_alias_source();
                $source =~ s/\(seq-policy in-word-progressive\)/(seq-policy in-word-progressive)\n      (seq-policy in-word-progressive)/;
                return $source;
            },
            qr/duplicate \(seq-policy \.\.\.\) clause/,
        ],
        [
            'unsupported seq policy',
            sub {
                my $source = sample_seq_alias_source();
                $source =~ s/\(seq-policy in-word-progressive\)/(seq-policy full-burst)/;
                return $source;
            },
            qr/transfer\.seq_policy must be in-word-progressive/,
        ],
        [
            'seq policy cannot widen supported-transfer scalar',
            sub {
                my $source = sample_seq_alias_source();
                $source =~ s/\(supported-transfer nonseq\)/(supported-transfer seq)/;
                return $source;
            },
            qr/transfer\.supported_transfer must be nonseq/,
        ],
    );

    for my $case (@cases) {
        my ($label, $build_source, $pattern) = @$case;
        my $path = File::Spec->catfile($tempdir, "$label.ahb");
        write_file($path, $build_source->());
        my $ok = eval { FSM::Adapter::IAL2::PPIF->new()->parse_file($path); 1 };
        ok(!$ok, "$label is rejected");
        like($@, $pattern, "$label diagnostic is targeted");
    }
};

subtest 'CLI JSON surfaces report byte-lane SEQ subordinate .ahb source identity and support accounting' => sub {
    my $check = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--check', '--json', sample_seq_alias_path());
    ok($check->{success}, '--check --json succeeds for byte-lane SEQ subordinate .ahb');
    is(
        $check->{source}{resolved_path},
        File::Spec->rel2abs(sample_seq_alias_path()),
        'byte-lane SEQ subordinate .ahb check JSON reports the public alias source path',
    );
    is($check->{result}{module_name}, 'ahb_lite_subordinate_byte_lane_seq', 'byte-lane SEQ subordinate .ahb check JSON reports generated module name');
    is($check->{support_accounting}{entry_id}, 'intent.ahb_profile_alias_subordinate_byte_lane_seq', 'byte-lane SEQ subordinate .ahb support accounting names the profile-alias corpus entry');
    is($check->{support_accounting}{source_kind}, 'ial2_profile_alias', 'byte-lane SEQ subordinate .ahb records profile-alias source kind');
    is($check->{support_accounting}{coverage}, 'ial2_ahb_profile_alias_subordinate_byte_lane_seq_pipeline_cli', 'byte-lane SEQ subordinate .ahb records selected coverage key');

    my $semantic = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--emit-semantic-json', sample_seq_alias_path());
    ok($semantic->{success}, '--emit-semantic-json succeeds for byte-lane SEQ subordinate .ahb');
    is(
        $semantic->{source}{resolved_path},
        File::Spec->rel2abs(sample_seq_alias_path()),
        'byte-lane SEQ subordinate .ahb semantic JSON reports the public alias source path',
    );
    is($semantic->{generation_result_snapshot}{summary}{module_name}, 'ahb_lite_subordinate_byte_lane_seq', 'byte-lane SEQ subordinate .ahb semantic JSON reports generated module name');
    is($semantic->{support_accounting}{entry_id}, 'intent.ahb_profile_alias_subordinate_byte_lane_seq', 'byte-lane SEQ subordinate .ahb semantic JSON support accounting names the profile-alias corpus entry');
    is($semantic->{support_accounting}{source_kind}, 'ial2_profile_alias', 'byte-lane SEQ subordinate .ahb semantic JSON records profile-alias source kind');
};

subtest 'schedule JSON and outdir expose byte-lane SEQ subordinate .ahb review artifacts' => sub {
    my $schedule = run_json_command('./bin/fsmgen', '--quiet', '--emit-schedule-json', sample_seq_alias_path());
    is($schedule->{schema}, 'fsmgen.ial2.protocol_intent.ahb_subordinate.v1', 'byte-lane SEQ subordinate .ahb schedule JSON reports the AHB subordinate schema');
    is($schedule->{target_protocol}{profile}, 'ahb', 'byte-lane SEQ subordinate .ahb schedule JSON reports the AHB profile');
    is($schedule->{target_protocol}{object}, 'ahb-subordinate', 'byte-lane SEQ subordinate .ahb schedule JSON reports the AHB subordinate object');
    is($schedule->{generated_artifacts}{ial1}{name}, 'ahb_lite_subordinate_byte_lane_seq.isf', 'byte-lane SEQ subordinate .ahb schedule JSON exposes generated IAL1 artifact');
    is_deeply($schedule->{generated_artifacts}{ial0}{files}, ['ahb_lite_subordinate_byte_lane_seq.fsm'], 'byte-lane SEQ subordinate .ahb schedule JSON exposes generated IAL0 artifact');
    is($schedule->{transfer}{seq_policy}{mode}, 'in_word_progressive', 'byte-lane SEQ subordinate .ahb schedule JSON exposes SEQ policy');
    is_deeply($schedule->{transfer}{seq_policy}{supported_sizes}, [qw(byte halfword)], 'byte-lane SEQ subordinate .ahb schedule JSON exposes SEQ supported sizes');
    my %schedule_residue = map { $_->{id} => $_->{detail} } @{$schedule->{unsupported_residue}};
    ok(!exists $schedule_residue{ahb_subordinate_profile_alias_deferred}, 'byte-lane SEQ subordinate .ahb schedule JSON removes stale profile-alias residue');
    unlike($schedule_residue{ahb_burst_seq_support_deferred}, qr/\.ahb alias exposure/, 'byte-lane SEQ subordinate .ahb schedule JSON removes alias-exposure residue wording');
    like($schedule_residue{ahb_burst_seq_support_deferred}, qr/aggregate propagation/, 'byte-lane SEQ subordinate .ahb schedule JSON keeps aggregate propagation deferred');

    my $tempdir = tempdir(CLEANUP => 1);
    my $outdir = File::Spec->catdir($tempdir, 'out');
    my $hdl = File::Spec->catfile($tempdir, 'ahb_lite_subordinate_byte_lane_seq.sv');
    my ($success, undef, undef, undef, $stderr) = run(
        command => ['./bin/fsmgen', '--quiet', '--outdir', $outdir, '--output', $hdl, sample_seq_alias_path()],
    );
    ok($success, 'byte-lane SEQ subordinate .ahb emits HDL and review artifacts through --outdir');
    is(join('', @{$stderr || []}), '', 'byte-lane SEQ subordinate .ahb outdir generation keeps stderr clean');
    ok(-f File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane_seq.isf'), 'outdir contains generated byte-lane SEQ IAL1 artifact');
    ok(-f File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane_seq.fsm'), 'outdir contains generated byte-lane SEQ IAL0 artifact');
    ok(-f $hdl, 'outdir command emits selected byte-lane SEQ subordinate HDL output');
    like(slurp(File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane_seq.isf')), qr/seq_expected_addr_q/, 'outdir generated .isf keeps expected-address state');
    like(slurp(File::Spec->catfile($outdir, 'ahb_lite_subordinate_byte_lane_seq.fsm')), qr/seq_write_q/, 'outdir generated .fsm keeps write-control stability state');
    like(slurp($hdl), qr/\bmodule\s+ahb_lite_subordinate_byte_lane_seq\b/, 'generated HDL contains byte-lane SEQ AHB subordinate module');
};

subtest 'existing generic SEQ, byte-lane, and word-only subordinate surfaces stay unchanged' => sub {
    my $seq_ppif = FSM::Adapter::IAL2::PPIF->new()->parse_file(sample_seq_ppif_path());
    my %seq_ppif_residue = map { $_->{id} => $_->{detail} } @{$seq_ppif->{report}{unsupported_residue}};
    ok($seq_ppif_residue{ahb_subordinate_profile_alias_deferred}, 'generic byte-lane SEQ PPIF still keeps .ahb alias residue explicit');
    like($seq_ppif_residue{ahb_burst_seq_support_deferred}, qr/\.ahb alias exposure/, 'generic byte-lane SEQ PPIF still names alias exposure deferred');
    is($seq_ppif->{report}{transfer}{seq_policy}{mode}, 'in_word_progressive', 'generic byte-lane SEQ PPIF keeps SEQ policy');

    my $byte_lane_alias = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--check', '--json', sample_byte_lane_alias_path());
    ok($byte_lane_alias->{success}, 'existing byte-lane subordinate .ahb alias still checks successfully');
    is($byte_lane_alias->{result}{module_name}, 'ahb_lite_subordinate_byte_lane', 'existing byte-lane subordinate .ahb alias keeps module name');
    is($byte_lane_alias->{support_accounting}{entry_id}, 'intent.ahb_profile_alias_subordinate_byte_lane', 'existing byte-lane subordinate .ahb alias keeps support identity');

    my $word_alias = run_json_command('./bin/fsmgen', '--quiet', '--strict', '--check', '--json', sample_word_only_alias_path());
    ok($word_alias->{success}, 'existing word-only subordinate .ahb alias still checks successfully');
    is($word_alias->{result}{module_name}, 'ahb_lite_subordinate', 'existing word-only subordinate .ahb alias keeps module name');
    is($word_alias->{support_accounting}{entry_id}, 'intent.ahb_profile_alias_subordinate', 'existing word-only subordinate .ahb alias keeps support identity');
};

done_testing();

sub sample_seq_ppif_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate_byte_lane_seq.ppif');
}

sub sample_seq_alias_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate_byte_lane_seq.ahb');
}

sub sample_byte_lane_alias_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate_byte_lane.ahb');
}

sub sample_word_only_alias_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'ahb_lite_subordinate.ahb');
}

sub sample_valid_ready_handshake_ppif_path {
    return File::Spec->catfile($FindBin::Bin, '..', 'ppif', 'valid_ready_handshake.ppif');
}

sub sample_seq_alias_source {
    return slurp(sample_seq_alias_path());
}

sub run_json_command {
    my @command = @_;
    my ($success, undef, undef, $stdout, $stderr) = run(command => \@command);
    my $json = join('', @{$stdout || []});
    my $decoded = eval { decode_json($json) };
    ok($decoded, join(' ', @command) . ' emits decodable JSON')
        or do {
            diag($json);
            diag(join('', @{$stderr || []}));
            diag('command failed') unless $success;
            return {};
        };
    return $decoded;
}

sub write_file {
    my ($path, $text) = @_;
    open my $fh, '>', $path or die "write $path: $!";
    print {$fh} $text;
    close $fh or die "close $path: $!";
}

sub slurp {
    my ($path) = @_;
    open my $fh, '<', $path or die "Cannot read $path: $!";
    local $/;
    return <$fh>;
}
