#!/usr/bin/env perl

use strict;
use warnings;
use Test::More;
use File::Spec;
use FindBin;

use lib File::Spec->catdir($FindBin::Bin, '..', 'perl');

use FSM::Support::DiagnosticCodes qw(
    diagnostic_code_ids
    diagnostic_code_metadata
    known_diagnostic_code
);
use FSM::Support::RegressionCorpus qw(regression_corpus_entries protocol_fixture_entries);

my $repo_root = File::Spec->catdir($FindBin::Bin, '..');
my @entries = regression_corpus_entries();
my @protocol_entries = protocol_fixture_entries();

ok(@entries >= 7, 'regression corpus catalog starts with named entries across multiple classifications');
ok(@entries >= 50, 'regression corpus catalog now covers supported language-feature fixtures plus root-level, section-level, child-root, direct-generation, and composition-contract residue families');
is(scalar(@protocol_entries), 118, 'first visible corpus slice contains the named protocol and public intent fixtures');

my %allowed_classifications = map { $_ => 1 } qw(
    supported_smoke
    expected_failure
    legacy_out_of_scope
);

my %allowed_coverages = map { $_ => 1 } qw(
    direct_root_pipeline_cli
    composition_top_pipeline_cli
    isf_pipeline_cli
    ial2_ppif_pipeline_cli
    ial2_ppif_bundle_pipeline_cli
    ial2_ppif_manager_capacity_status_pipeline_cli
    ial2_ppif_manager_capacity_status_id_family_pipeline_cli
    ial2_ppif_manager_capacity_status_transaction_envelope_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_transaction_id_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_write_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_write_response_demux_multi_pipeline_cli
    ial2_ppif_manager_capacity_status_write_mixed_dynamic_static_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_static_pipeline_cli
    ial2_ppif_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_static3_pipeline_cli
    ial2_ppif_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_dynamic_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last_read_data_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last_read_data_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last_read_data_multi_beat_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_multi_beat_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_multi_beat_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_multi_beat_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_response_demux_multi_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_response_demux_multi_burst_last_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_response_demux_burst_last_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_data_last_beat_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_last_beat_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_transaction_multi_beat_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_data_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_data_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_beat_pipeline_cli
    ial2_ppif_manager_capacity_status_transaction_event_dispatch_pipeline_cli
    ial2_ppif_manager_capacity_status_same_id_reject_policy_pipeline_cli
    ial2_ppif_manager_capacity_status_same_id_issue_order_queue_policy_pipeline_cli
    ial2_ppif_manager_capacity_status_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_depth3_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_multi_depth3_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_mixed_depth3_depth2_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_mixed_auto_id_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_multi_beat_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_multi_beat_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_multi_beat_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_multi_beat_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_depth3_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_multi_depth3_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_mixed_depth3_depth2_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_mixed_auto_id_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_multi_group_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_single_beat_multi_group_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_last_beat_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_last_beat_same_id_queue_head_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_last_beat_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_multi_beat_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_multi_group_same_id_queue_head_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_multi_group_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_write_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_write_depth3_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_write_multi_depth3_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_write_mixed_depth3_depth2_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_write_mixed_auto_id_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_write_multi_group_same_id_queue_head_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_auto_id_lifecycle_pipeline_cli
    ial2_ppif_manager_capacity_status_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_response_demux_pipeline_cli
    ial2_ppif_manager_capacity_status_read_response_demux_burst_last_pipeline_cli
    ial2_ppif_manager_capacity_status_read_data_pipeline_cli
    ial2_ppif_manager_capacity_status_read_data_last_beat_pipeline_cli
    ial2_ppif_manager_capacity_status_read_data_burst_length_pipeline_cli
    ial2_ppif_manager_capacity_status_read_data_burst_length_runtime_assertion_pipeline_cli
    ial2_ppif_manager_capacity_status_read_data_multi_beat_pipeline_cli
    legacy_root_default_pipeline_cli
    legacy_section_default_pipeline_cli
    legacy_assignment_default_pipeline_cli
    legacy_child_root_default_pipeline_cli
    legacy_composition_default_pipeline_cli
    strict_root_rejection_pipeline_cli
    strict_section_rejection_pipeline_cli
    strict_assignment_rejection_pipeline_cli
    strict_child_root_rejection_pipeline_cli
    strict_composition_rejection_pipeline_cli
    language_contract_rejection_pipeline_cli
    direct_generation_contract_rejection_pipeline_cli
    composition_contract_rejection_pipeline_cli
);

my %allowed_target_languages = map { $_ => 1 } qw(
    systemverilog
    sv
    verilog
    v
    vhdl
);

my %strict_rejection_coverages = map { $_ => 1 } qw(
    strict_root_rejection_pipeline_cli
    strict_section_rejection_pipeline_cli
    strict_assignment_rejection_pipeline_cli
    strict_child_root_rejection_pipeline_cli
    strict_composition_rejection_pipeline_cli
);

my %coverage_classification = (
    direct_root_pipeline_cli => 'supported_smoke',
    composition_top_pipeline_cli => 'supported_smoke',
    isf_pipeline_cli => 'supported_smoke',
    ial2_ppif_pipeline_cli => 'supported_smoke',
    ial2_ppif_bundle_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_id_family_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_transaction_envelope_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_transaction_id_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_write_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_write_response_demux_multi_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_write_mixed_dynamic_static_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_static_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_static3_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_dynamic_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last_read_data_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last_read_data_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last_read_data_multi_beat_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_multi_beat_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_multi_beat_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_multi_beat_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_response_demux_multi_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_response_demux_multi_burst_last_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_response_demux_burst_last_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_data_last_beat_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_last_beat_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_transaction_multi_beat_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_data_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_data_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_dynamic_read_data_multi_beat_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_transaction_event_dispatch_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_same_id_reject_policy_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_same_id_issue_order_queue_policy_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_depth3_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_multi_depth3_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_mixed_depth3_depth2_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_mixed_auto_id_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_multi_beat_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_multi_beat_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_multi_beat_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_multi_beat_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_depth3_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_multi_depth3_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_mixed_depth3_depth2_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_mixed_auto_id_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_multi_group_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_single_beat_multi_group_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_last_beat_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_last_beat_same_id_queue_head_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_last_beat_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_multi_beat_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_multi_group_same_id_queue_head_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_multi_group_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_write_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_write_depth3_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_write_multi_depth3_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_write_mixed_depth3_depth2_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_write_mixed_auto_id_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_write_multi_group_same_id_queue_head_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_auto_id_lifecycle_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_response_demux_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_response_demux_burst_last_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_data_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_data_last_beat_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_data_burst_length_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_data_burst_length_runtime_assertion_pipeline_cli => 'supported_smoke',
    ial2_ppif_manager_capacity_status_read_data_multi_beat_pipeline_cli => 'supported_smoke',
    legacy_root_default_pipeline_cli => 'legacy_out_of_scope',
    legacy_section_default_pipeline_cli => 'legacy_out_of_scope',
    legacy_assignment_default_pipeline_cli => 'legacy_out_of_scope',
    legacy_child_root_default_pipeline_cli => 'legacy_out_of_scope',
    legacy_composition_default_pipeline_cli => 'legacy_out_of_scope',
    strict_root_rejection_pipeline_cli => 'expected_failure',
    strict_section_rejection_pipeline_cli => 'expected_failure',
    strict_assignment_rejection_pipeline_cli => 'expected_failure',
    strict_child_root_rejection_pipeline_cli => 'expected_failure',
    strict_composition_rejection_pipeline_cli => 'expected_failure',
    language_contract_rejection_pipeline_cli => 'expected_failure',
    direct_generation_contract_rejection_pipeline_cli => 'expected_failure',
    composition_contract_rejection_pipeline_cli => 'expected_failure',
);

my %seen_ids;
my %seen_contracts;
my %seen_diagnostic_codes;
my %by_id = map { $_->{id} => $_ } @entries;

for my $required_id (qw(
    protocol.apb_requester
    protocol.apb_completer
    protocol.amba_requester
    protocol.apb_tb
    intent.isf_apb_requester
    intent.ppif_axi_aw_valid_ready
    intent.ppif_axi_aw_w_valid_ready_bundle
    intent.ppif_axi_manager_capacity_status
    intent.ppif_axi_manager_capacity_status_id_family
    intent.ppif_axi_manager_capacity_status_transaction_envelope
    intent.ppif_axi_manager_capacity_status_dynamic_transaction_id
    intent.ppif_axi_manager_capacity_status_dynamic_write_response_demux
    intent.ppif_axi_manager_capacity_status_dynamic_write_response_demux_multi
    intent.ppif_axi_manager_capacity_status_write_mixed_dynamic_static_response_demux
    intent.ppif_axi_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_static
    intent.ppif_axi_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_static3
    intent.ppif_axi_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_dynamic
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_multi_beat
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_burst_length
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_multi_beat
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_burst_length
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_multi_beat
    intent.ppif_axi_manager_capacity_status_dynamic_read_response_demux
    intent.ppif_axi_manager_capacity_status_dynamic_read_response_demux_multi
    intent.ppif_axi_manager_capacity_status_dynamic_read_response_demux_multi_burst_last
    intent.ppif_axi_manager_capacity_status_dynamic_read_response_demux_burst_last
    intent.ppif_axi_manager_capacity_status_dynamic_read_data
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_last_beat
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi_last_beat
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi_burst_length
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi_transaction_multi_beat
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_burst_length
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi_beat
    intent.ppif_axi_manager_capacity_status_transaction_event_dispatch
    intent.ppif_axi_manager_capacity_status_same_id_reject_policy
    intent.ppif_axi_manager_capacity_status_same_id_issue_order_queue_policy
    intent.ppif_axi_manager_capacity_status_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_multi_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_mixed_depth3_depth2_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_mixed_auto_id_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_multi_beat_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_multi_beat_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_multi_beat_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_multi_beat_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_depth3_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_multi_depth3_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_mixed_depth3_depth2_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_mixed_auto_id_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_multi_group_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_multi_group_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_last_beat_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_last_beat_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_last_beat_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_multi_beat_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_multi_group_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_multi_group_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_multi_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_mixed_depth3_depth2_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_mixed_auto_id_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_multi_group_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_auto_id_lifecycle
    intent.ppif_axi_manager_capacity_status_response_demux
    intent.ppif_axi_manager_capacity_status_read_response_demux
    intent.ppif_axi_manager_capacity_status_read_response_demux_burst_last
    intent.ppif_axi_manager_capacity_status_read_data
    intent.ppif_axi_manager_capacity_status_read_data_last_beat
    intent.ppif_axi_manager_capacity_status_read_data_burst_length
    intent.ppif_axi_manager_capacity_status_read_data_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_data_multi_beat
    feature.isf_verification_observation_metadata
    feature.isf_storage_field_metadata
    feature.partial_lhs_with_size
    feature.partial_lhs_inferred_width
    feature.direct_rhs_concat_pack
    feature.direct_rhs_concat_target_autogrowth
    feature.direct_lhs_deconstruct_pack
    feature.direct_sreset_active_high
    feature.custom_system_clock
    feature.implicit_system_defaults
    feature.direct_areset_active_low
    feature.reset_state_aliases
    feature.direct_canonical_init_directive
    feature.direct_size_expression_widths
    feature.declarative_bits_symbol_widths
    feature.direct_aggregate_constant_target_autogrowth
    feature.direct_runtime_div_mod
    feature.params_aggregate_unary_complement
    feature.arithmetic_xor_operator_variants
    feature.rhs_expression_supported_variants
    feature.direct_assignment_pair_form
    feature.update_shorthand_variants
    feature.compound_update_variants
    feature.state_dte_guards
    feature.standalone_dt_guards
    feature.standalone_dt_explicit_system
    feature.guard_shorthand
    feature.nested_compound_guards
    feature.relational_operator_chains
    feature.computed_test_selector
    feature.computed_comparison_selector
    feature.plain_test_signal_selectors
    feature.test_selector_symbolic_default
    feature.test_branch_selectors
    feature.direct_intent_integer_literals
    feature.composition_intent_integer_literals
    feature.implicit_composition_system_autowire
    feature.standalone_dtc_explicit_system_autowire
    legacy.mipicsi2_txccore_ulp.default_compat
    legacy.mipicsi2_txccore_ulp.strict_rejection
    legacy.empty_size_noop.default_compat
    legacy.empty_size_noop.strict_rejection
    legacy.asreset_rstn.default_compat
    legacy.asreset_rstn.strict_rejection
    legacy.sreset_rstn.default_compat
    legacy.sreset_rstn.strict_rejection
    legacy.compact_init_directive.default_compat
    legacy.compact_init_directive.strict_rejection
    legacy.infix_assignment.default_compat
    legacy.infix_assignment.strict_rejection
    legacy.lteplus_assignment.default_compat
    legacy.lteplus_assignment.strict_rejection
    legacy.fsm_child_root.default_compat
    legacy.fsm_child_root.strict_rejection
    legacy.dt_child_root.default_compat
    legacy.dt_child_root.strict_rejection
    legacy.composition_wiring_slash.default_compat
    legacy.composition_wiring_slash.strict_rejection
    contract.language_contract_bad_size_entry
    contract.direct_size_expression_non_positive
    contract.direct_size_expression_unknown_symbol
    contract.direct_size_expression_aggregate_symbol
    contract.direct_size_expression_divide_by_zero
    contract.direct_size_expression_modulo_by_zero
    contract.direct_size_expression_unsupported_operator
    contract.direct_size_expression_bad_arity
    contract.direct_lhs_deconstruct_width_mismatch
    contract.unsupported_top_level_define_source
    contract.generic_fifo_define_template_source
    contract.unsupported_top_level_clock_directive
    contract.unsupported_top_level_infix_init_form
    contract.unsupported_top_level_bare_scalar_form
    contract.generic_placeholder_selector
    contract.generic_repeat_macro
    contract.generic_placeholder_token
    contract.bare_assignment_condition_suffix
    contract.bare_transition_condition_suffix
    contract.malformed_top_level_system_root
    contract.malformed_single_token_action
    contract.malformed_empty_guard
    contract.malformed_empty_test_branch
    contract.malformed_bare_symbolic_test_selector
    contract.malformed_bare_numeric_test_selector
    contract.test_selector_duplicate_default
    contract.system_incomplete_section
    contract.system_duplicate_clock_entry
    contract.system_duplicate_reset_declaration
    contract.system_malformed_entry_structure
    contract.system_bad_clock_identifier
    contract.system_bad_reset_identifier
    contract.malformed_fsm_source_name
    contract.malformed_empty_fsm_root_body
    contract.malformed_scalar_fsm_root_body_item
    contract.malformed_top_source_name
    contract.malformed_state_name
    contract.malformed_standalone_dt_name
    contract.malformed_empty_state_body
    contract.malformed_empty_standalone_dt_body
    contract.malformed_transition_target
    contract.unknown_transition_target
    contract.rhs_expression_unsupported_operator
    contract.rhs_expression_bad_arity
    contract.direct_runtime_divide_literal_zero
    contract.direct_runtime_modulo_exact_zero
    contract.rhs_expression_guard_token
    contract.condition_guard_payload_missing_rhs
    contract.condition_guard_payload_missing_lhs
    contract.condition_inline_comparison_missing_rhs
    contract.condition_inline_comparison_missing_lhs
    contract.assignment_delayed_pulse_bad_rhs
    contract.delayed_pulse_lhs_index
    contract.delayed_pulse_lhs_range
    contract.delayed_pulse_lhs_pair_index
    contract.assignment_mixed_comb_seq
    contract.assignment_mixed_pulse_nonpulse
    contract.assignment_multiple_pulse_delays
    contract.assignment_comb_self_dependency
    contract.assignment_d_input_self_dependency
    contract.operator_unsupported_qeq
    contract.operator_unsupported_arrow
    contract.directive_init_placeholder_value
    contract.directive_init_guard_value
    contract.init_directive_payload_extra
    contract.init_directive_compact_broken
    contract.init_directive_canonical_missing_value
    contract.symbol_empty_constants_section
    contract.symbol_empty_define_directive
    contract.symbol_empty_params_section
    contract.symbol_empty_enums_section
    contract.symbol_bad_constants_entry
    contract.symbol_bad_define_entry
    contract.symbol_bad_params_entry
    contract.symbol_bad_enums_member
    contract.symbol_param_unresolved_value
    contract.symbol_constants_ambiguous_bitstring_value
    contract.symbol_params_ambiguous_bitstring_value
    contract.params_dependency_cycle
    contract.params_duplicate_declaration
    contract.params_aggregate_arithmetic_mixed_operand
    contract.params_aggregate_bitwise_mixed_operand
    contract.params_aggregate_shape_mismatch
    contract.params_aggregate_overflow
    contract.params_aggregate_underflow
    contract.params_aggregate_divide_by_zero
    contract.symbol_bad_constants_identifier
    contract.symbol_bad_define_identifier
    contract.symbol_bad_params_identifier
    contract.symbol_bad_enum_member_value
    contract.plus_fsm_empty_body
    contract.plus_fsm_scalar_body_item
    contract.test_signal_bad_hyphen
    contract.test_signal_numeric
    contract.computed_test_missing_expr
    contract.inline_modifier_malformed_payload
    contract.inline_modifier_duplicate
    contract.update_shorthand_nested_prefix_target
    contract.update_shorthand_nested_separated_target
    contract.update_shorthand_tail_single
    contract.update_shorthand_tail_multi
    contract.direct_rhs_concat_width_mismatch
    contract.direct_aggregate_contract_mismatch
    contract.composition_child_structure_empty_entry
    contract.composition_child_header_nonstring
    contract.composition_child_item_list_dotted_fsmc
    contract.composition_child_item_list_dotted_wiring
    contract.composition_child_item_list_dotted_ports
    contract.composition_child_item_list_dotted_dtc
    contract.composition_child_item_list_dotted_rtl
    contract.composition_unsupported_child_kind
    contract.composition_ports_mapping_directive
    contract.trial_2_ports_mapping_directive
    contract.composition_duplicate_top_port
    contract.composition_duplicate_child_instance
    contract.composition_ports_shape_multiple_blocks
    contract.composition_ports_shape_missing_ports
    contract.composition_ports_shape_empty_ports
    contract.composition_target_support_vhdl
    contract.composition_missing_explicit_wiring
    contract.composition_c1_missing_exposure
    contract.composition_c1_unknown_top_port
    contract.composition_c1_width_mismatch
    contract.composition_c1_direction_mismatch
    contract.composition_system_port_same_name
    contract.composition_child_endpoint_missing_aggregate_type
    contract.composition_ports_verbose_declaration_shape
    contract.composition_ports_invalid_token
    contract.composition_ports_nonpositive_width
    contract.composition_wiring_wrapped_slash_item
    contract.composition_wiring_unsupported_token
    contract.composition_top_constants_bad_identifier
    contract.composition_top_enums_nonliteral_value
    contract.missing_rtl_metadata_sidecar
    contract.missing_fsm_child_source
    contract.missing_dt_child_source
    contract.wrong_kind_fsm_child_source
    contract.wrong_kind_dt_child_source
    contract.generated_child_source_count_fsmc
    contract.generated_child_source_count_dtc
    contract.generated_child_source_shape_fsmc
    contract.generated_child_source_shape_dtc
    contract.rtl_child_source_shape_nested
    contract.rtl_child_source_count_multi_token
    contract.lte_digital_rf_rtl_child_source_count
    contract.invalid_rtl_system_port_direction
    contract.duplicate_rtlif_port_declaration
    contract.invalid_rtlif_port_type
    contract.invalid_rtlif_port_token
    contract.invalid_rtlif_port_width
    contract.missing_rtlif_root
    contract.empty_rtlif_port_declaration
    contract.nested_rtlif_port_declaration
    contract.duplicate_embedded_rtlif_root
)) {
    ok($by_id{$required_id}, "catalog keeps required entry $required_id");
}

for my $entry (@entries) {
    ok(!$seen_ids{$entry->{id}}++, "catalog entry id '$entry->{id}' is unique");
    my $contract_key = join "\0", $entry->{relpath}, $entry->{classification}, $entry->{coverage};
    ok(!$seen_contracts{$contract_key}++, "catalog contract for '$entry->{id}' is unique");
    ok($allowed_classifications{$entry->{classification}}, "catalog entry '$entry->{id}' uses a known classification");
    ok($allowed_coverages{$entry->{coverage}}, "catalog entry '$entry->{id}' uses a known coverage bucket");
    if (exists $entry->{target_language}) {
        ok($allowed_target_languages{$entry->{target_language}},
            "catalog entry '$entry->{id}' uses a known target language override");
    }
    is(
        $coverage_classification{$entry->{coverage}},
        $entry->{classification},
        "catalog entry '$entry->{id}' keeps classification and coverage aligned",
    );

    my $path = File::Spec->catfile($repo_root, split m{/}, $entry->{relpath});
    ok(-e $path, "catalog entry '$entry->{id}' points at an existing repo file");
    if (ref($entry->{search_path_relpaths}) eq 'ARRAY') {
        for my $relpath (@{$entry->{search_path_relpaths}}) {
            my $search_path = File::Spec->catfile($repo_root, split m{/}, $relpath);
            ok(-d $search_path, "catalog entry '$entry->{id}' points at an existing search path '$relpath'");
        }
    }

    if ($entry->{classification} eq 'expected_failure') {
        like(
            $entry->{diagnostic_code} || '',
            qr/\AFSMGEN_[A-Z0-9_]+\z/,
            "expected-failure entry '$entry->{id}' records a stable diagnostic code",
        );
        ok(
            known_diagnostic_code($entry->{diagnostic_code}),
            "expected-failure entry '$entry->{id}' uses a known diagnostic code",
        );
        my $diagnostic_metadata = diagnostic_code_metadata($entry->{diagnostic_code});
        is(
            $diagnostic_metadata->{severity},
            'error',
            "expected-failure entry '$entry->{id}' maps to an error diagnostic",
        ) if $diagnostic_metadata;
        is(
            $diagnostic_metadata->{stability},
            'stable',
            "expected-failure entry '$entry->{id}' maps to a stable diagnostic",
        ) if $diagnostic_metadata;
        $seen_diagnostic_codes{$entry->{diagnostic_code}}++ if $entry->{diagnostic_code};
        ok($entry->{expected_error_pattern}, "expected-failure entry '$entry->{id}' records a boundary pattern");
        ok(ref($entry->{expected_error_pattern}) eq 'Regexp',
            "expected-failure entry '$entry->{id}' records its boundary pattern as a compiled regex");
        if (exists $entry->{expected_hint_pattern}) {
            ok($entry->{expected_hint_pattern}, "expected-failure entry '$entry->{id}' records a migration-hint pattern");
            ok(ref($entry->{expected_hint_pattern}) eq 'Regexp',
                "expected-failure entry '$entry->{id}' records its migration-hint pattern as a compiled regex");
        }
        if ($strict_rejection_coverages{$entry->{coverage}}) {
            ok(
                ref($entry->{expected_hint_pattern}) eq 'Regexp',
                "strict-rejection entry '$entry->{id}' records a compiled migration-hint pattern",
            );
        }
    }
    elsif (exists $entry->{diagnostic_code}) {
        fail("non-failure catalog entry '$entry->{id}' must not reserve a diagnostic code");
    }
    elsif (
        $entry->{source_kind} eq 'fsm'
            || $entry->{source_kind} eq 'dt'
            || $entry->{source_kind} eq 'isf'
            || $entry->{source_kind} eq 'ppif'
    ) {
        ok($entry->{expected_module_name}, "direct or intent entry '$entry->{id}' records an expected module name");
    }
    elsif ($entry->{source_kind} eq 'composition') {
        ok($entry->{expected_top_name}, "composition entry '$entry->{id}' records an expected top name");
        ok($entry->{expected_lane}, "composition entry '$entry->{id}' records an expected composition lane");
        ok($entry->{expected_instance_count} >= 1, "composition entry '$entry->{id}' records a positive child count");
        ok(ref($entry->{expected_child_modules}) eq 'ARRAY',
            "composition entry '$entry->{id}' records expected child modules as an array");
    }
    else {
        fail("catalog entry '$entry->{id}' uses an unsupported source kind '$entry->{source_kind}'");
    }

    if (exists $entry->{expected_hdl_patterns}) {
        ok(ref($entry->{expected_hdl_patterns}) eq 'ARRAY',
            "catalog entry '$entry->{id}' records HDL-shape patterns as an array");
        if (ref($entry->{expected_hdl_patterns}) eq 'ARRAY') {
            my $pattern_index = 0;
            for my $pattern (@{$entry->{expected_hdl_patterns}}) {
                ok(ref($pattern) eq 'Regexp',
                    "catalog entry '$entry->{id}' HDL-shape pattern $pattern_index is a compiled regex");
                ++$pattern_index;
            }
        }
    }

    if (
        $entry->{family} eq 'language_feature_fixture'
            && $entry->{classification} eq 'supported_smoke'
            && $entry->{coverage} eq 'direct_root_pipeline_cli'
    ) {
        ok(
            ref($entry->{expected_hdl_patterns}) eq 'ARRAY'
                && @{$entry->{expected_hdl_patterns}},
            "supported direct language-feature fixture '$entry->{id}' records explicit HDL-shape patterns",
        );
    }

    if ($entry->{strict_supported}) {
        is($entry->{classification}, 'supported_smoke', "strict-supported entry '$entry->{id}' is a supported-smoke asset");
        ok(
            $entry->{source_kind} eq 'fsm' || $entry->{source_kind} eq 'dt',
            "strict-supported direct entry '$entry->{id}' is a direct-root corpus asset",
        )
            if $entry->{coverage} eq 'direct_root_pipeline_cli';
        ok(
            ($coverage_classification{$entry->{coverage}} || '') eq 'supported_smoke',
            "strict-supported entry '$entry->{id}' keeps pipeline/CLI coverage",
        );
    }
}

is(
    scalar(grep { $_->{classification} eq 'supported_smoke' } @entries),
    157,
    'catalog now keeps one hundred fifty-seven named supported-smoke entries including direct, composition, ISF, and PPIF fixtures',
);
is(
    scalar(grep { $_->{classification} eq 'legacy_out_of_scope' } @entries),
    10,
    'catalog now records ten explicit legacy-out-of-scope compatibility entries',
);
is(
    scalar(grep { $_->{classification} eq 'expected_failure' } @entries),
    164,
    'catalog now records one hundred sixty-four explicit expected-failure entries',
);
is(
    scalar(grep { $_->{strict_supported} } @entries),
    157,
    'catalog now records one hundred fifty-seven positive strict-mode supported-smoke acceptance entries',
);
for my $strict_supported_id (qw(
    protocol.apb_requester
    protocol.apb_completer
    protocol.amba_requester
    protocol.apb_tb
    intent.isf_apb_requester
    intent.ppif_axi_aw_valid_ready
    intent.ppif_axi_aw_w_valid_ready_bundle
    intent.ppif_axi_manager_capacity_status
    intent.ppif_axi_manager_capacity_status_id_family
    intent.ppif_axi_manager_capacity_status_transaction_envelope
    intent.ppif_axi_manager_capacity_status_dynamic_transaction_id
    intent.ppif_axi_manager_capacity_status_dynamic_write_response_demux
    intent.ppif_axi_manager_capacity_status_dynamic_write_response_demux_multi
    intent.ppif_axi_manager_capacity_status_write_mixed_dynamic_static_response_demux
    intent.ppif_axi_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_static
    intent.ppif_axi_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_static3
    intent.ppif_axi_manager_capacity_status_write_mixed_dynamic_static_response_demux_multi_dynamic
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_dynamic_burst_last
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_burst_length
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static3_burst_last_read_data_multi_beat
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_burst_length
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_multi_static_burst_last_read_data_multi_beat
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_burst_length
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_mixed_dynamic_static_response_demux_burst_last_read_data_multi_beat
    intent.ppif_axi_manager_capacity_status_dynamic_read_response_demux
    intent.ppif_axi_manager_capacity_status_dynamic_read_response_demux_multi
    intent.ppif_axi_manager_capacity_status_dynamic_read_response_demux_multi_burst_last
    intent.ppif_axi_manager_capacity_status_dynamic_read_response_demux_burst_last
    intent.ppif_axi_manager_capacity_status_dynamic_read_data
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_last_beat
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi_last_beat
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi_burst_length
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi_transaction_multi_beat
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_burst_length
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_dynamic_read_data_multi_beat
    intent.ppif_axi_manager_capacity_status_transaction_event_dispatch
    intent.ppif_axi_manager_capacity_status_same_id_reject_policy
    intent.ppif_axi_manager_capacity_status_same_id_issue_order_queue_policy
    intent.ppif_axi_manager_capacity_status_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_multi_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_mixed_depth3_depth2_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_mixed_auto_id_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_auto_id_same_id_queue_head_multi_beat_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_burst_last_depth3_same_id_queue_head_multi_beat_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_multi_depth3_same_id_queue_head_multi_beat_read_data
    intent.ppif_axi_manager_capacity_status_read_burst_last_mixed_depth3_depth2_same_id_queue_head_multi_beat_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_depth3_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_multi_depth3_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_mixed_depth3_depth2_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_multi_group_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_read_single_beat_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_single_beat_multi_group_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_last_beat_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_last_beat_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_last_beat_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_multi_beat_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_burst_length
    intent.ppif_axi_manager_capacity_status_read_multi_group_last_beat_same_id_queue_head_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_multi_group_same_id_queue_head_read_data
    intent.ppif_axi_manager_capacity_status_read_multi_group_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_multi_depth3_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_mixed_depth3_depth2_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_mixed_auto_id_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_write_multi_group_same_id_queue_head_response_demux
    intent.ppif_axi_manager_capacity_status_auto_id_lifecycle
    intent.ppif_axi_manager_capacity_status_response_demux
    intent.ppif_axi_manager_capacity_status_read_response_demux
    intent.ppif_axi_manager_capacity_status_read_response_demux_burst_last
    intent.ppif_axi_manager_capacity_status_read_data
    intent.ppif_axi_manager_capacity_status_read_data_last_beat
    intent.ppif_axi_manager_capacity_status_read_data_burst_length
    intent.ppif_axi_manager_capacity_status_read_data_burst_length_runtime_assertion
    intent.ppif_axi_manager_capacity_status_read_data_multi_beat
    feature.isf_verification_observation_metadata
    feature.isf_storage_field_metadata
    feature.partial_lhs_with_size
    feature.partial_lhs_inferred_width
    feature.direct_rhs_concat_pack
    feature.direct_rhs_concat_target_autogrowth
    feature.direct_lhs_deconstruct_pack
    feature.direct_sreset_active_high
    feature.custom_system_clock
    feature.implicit_system_defaults
    feature.direct_areset_active_low
    feature.reset_state_aliases
    feature.direct_canonical_init_directive
    feature.direct_size_expression_widths
    feature.declarative_bits_symbol_widths
    feature.direct_aggregate_constant_target_autogrowth
    feature.direct_runtime_div_mod
    feature.arithmetic_xor_operator_variants
    feature.rhs_expression_supported_variants
    feature.direct_assignment_pair_form
    feature.update_shorthand_variants
    feature.compound_update_variants
    feature.state_dte_guards
    feature.standalone_dt_guards
    feature.standalone_dt_explicit_system
    feature.guard_shorthand
    feature.nested_compound_guards
    feature.relational_operator_chains
    feature.computed_test_selector
    feature.computed_comparison_selector
    feature.plain_test_signal_selectors
    feature.test_selector_symbolic_default
    feature.test_branch_selectors
    feature.direct_intent_integer_literals
    feature.composition_intent_integer_literals
    feature.implicit_composition_system_autowire
    feature.standalone_dtc_explicit_system_autowire
)) {
    ok($by_id{$strict_supported_id}->{strict_supported}, "canonical strict-supported fixture $strict_supported_id stays marked");
}

for my $diagnostic_code (diagnostic_code_ids()) {
    ok($seen_diagnostic_codes{$diagnostic_code}, "stable diagnostic code $diagnostic_code is exercised by the corpus");
}

for my $entry (
    grep {
        $_->{family} eq 'language_feature_fixture'
            && $_->{classification} eq 'supported_smoke'
    } @entries
) {
    ok($entry->{strict_supported}, "supported language-feature fixture '$entry->{id}' is strict-supported");
}

for my $entry (
    grep {
        $_->{family} eq 'protocol_fixture'
            && $_->{classification} eq 'supported_smoke'
    } @entries
) {
    ok($entry->{strict_supported}, "supported protocol fixture '$entry->{id}' is strict-supported");
}

done_testing();
