package FSM::Support::RegressionCorpus;

use strict;
use warnings;

use Exporter 'import';

our @EXPORT_OK = qw(regression_corpus_entries protocol_fixture_entries);

my @REGRESSION_CORPUS = (
    {
        id => 'protocol.apb_requester',
        relpath => 'fsm/apb_requester.fsm',
        family => 'protocol_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'apb_requester',
    },
    {
        id => 'protocol.apb_completer',
        relpath => 'fsm/apb_completer.fsm',
        family => 'protocol_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'apb_completer',
    },
    {
        id => 'protocol.amba_requester',
        relpath => 'fsm/amba_requester.fsm',
        family => 'protocol_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'amba_requester',
    },
    {
        id => 'protocol.apb_tb',
        relpath => 'fsm/apb_tb.fsm',
        family => 'protocol_fixture',
        classification => 'supported_smoke',
        coverage => 'composition_top_pipeline_cli',
        source_kind => 'composition',
        strict_supported => 1,
        expected_top_name => 'apb_tb',
        expected_lane => 'C4',
        expected_instance_count => 2,
        expected_child_modules => ['apb_requester', 'apb_completer'],
    },
    {
        id => 'feature.partial_lhs_with_size',
        relpath => 't/corpus/partial_lhs_with_size.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'partial_lhs_with_size',
        expected_hdl_patterns => [
            qr/\bOUT\s*=\s*\{HI,\s*MID,\s*LO\};/s,
            qr/\bROD_next\s*=\s*\{HI,\s*MID,\s*LO\};/s,
            qr/\bRIP\s*=\s*\{HI,\s*MID,\s*LO\};/s,
            qr/\bRID\s*=\s*\{HI,\s*MID,\s*LO\};/s,
            qr/\boutput\s+reg\s+\[3:0\]\s+next_ROD\b/s,
            qr/\boutput\s+reg\s+\[3:0\]\s+RIP_r\b/s,
            qr/\boutput\s+reg\s+\[3:0\]\s+RID_r\b/s,
        ],
    },
    {
        id => 'feature.partial_lhs_inferred_width',
        relpath => 't/corpus/partial_lhs_inferred_width.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'partial_lhs_inferred_width',
        expected_hdl_patterns => [
            qr/\breg\s+\[3:0\]\s+OUT;/s,
            qr/\boutput\s+reg\s+\[3:0\]\s+next_ROD\b/s,
            qr/\boutput\s+reg\s+\[3:0\]\s+RIP_r\b/s,
            qr/\boutput\s+reg\s+\[3:0\]\s+RID_r\b/s,
            qr/\breg\s+\[4:0\]\s+IDXOUT;/s,
            qr/\boutput\s+reg\s+\[4:0\]\s+next_IDXRO\b/s,
            qr/\boutput\s+reg\s+\[4:0\]\s+IDXRIP_r\b/s,
            qr/\boutput\s+reg\s+\[4:0\]\s+IDXRI_r\b/s,
        ],
    },
    {
        id => 'feature.direct_rhs_concat_pack',
        relpath => 't/corpus/direct_rhs_concat_pack.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'direct_rhs_concat_pack',
        expected_hdl_patterns => [
            qr/\bOUT\s*=\s*\{HI,\s*MID,\s*LO\};/s,
            qr/\bOUT_CAT\s*=\s*\{HI,\s*MID,\s*LO\};/s,
            qr/\bOUT_NESTED\s*=\s*\{HI,\s*\{MID,\s*LO\}\};/s,
        ],
    },
    {
        id => 'feature.direct_lhs_deconstruct_pack',
        relpath => 't/corpus/direct_lhs_deconstruct_pack.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'direct_lhs_deconstruct_pack',
        expected_hdl_patterns => [
            qr/\bHI\s*=\s*DATA\[7:4\];/s,
            qr/\bLO\s*=\s*DATA\[3:0\];/s,
            qr/\bCAT_HI\s*=\s*DATA2\[7:4\];/s,
            qr/\bCAT_LO\s*=\s*DATA2\[3:0\];/s,
            qr/\bOUT\s*=\s*\{DATA\[7:4\],\s*DATA\[3:0\]\};/s,
        ],
    },
    {
        id => 'feature.direct_sreset_active_high',
        relpath => 't/corpus/direct_sreset_active_high.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'direct_sreset_active_high',
        expected_hdl_patterns => [
            qr/\binput\s+wire\s+reset\b/s,
            qr/always_ff\s*@\(posedge\s+clk\)\s*begin\s+if\s*\(reset\)\s*begin/s,
        ],
    },
    {
        id => 'feature.direct_areset_active_low',
        relpath => 't/corpus/direct_areset_active_low.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'direct_areset_active_low',
        expected_hdl_patterns => [
            qr/\binput\s+wire\s+rst_n\b/s,
            qr/always_ff\s*@\(posedge\s+clk\s+or\s+negedge\s+rst_n\)\s*begin\s+if\s*\(!rst_n\)\s*begin/s,
        ],
    },
    {
        id => 'feature.direct_canonical_init_directive',
        relpath => 't/corpus/direct_canonical_init_directive.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'direct_canonical_init_directive',
        expected_hdl_patterns => [
            qr/always_ff\s*@\(posedge\s+clk\)\s*begin\s+if\s*\(reset\)\s*begin\s+A_q\s*<=\s*1'b1;/s,
        ],
    },
    {
        id => 'feature.direct_size_expression_widths',
        relpath => 't/corpus/direct_size_expression_widths.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'direct_size_expression_widths',
        expected_hdl_patterns => [
            qr/parameter\s+PARAM_W\s*=\s*\(2\s*\+\s*1\)/s,
            qr/\breg\s+\[2:0\]\s+A;/s,
            qr/\breg\s+\[3:0\]\s+B;/s,
            qr/\breg\s+\[7:0\]\s+C;/s,
            qr/\breg\s+\[3:0\]\s+D;/s,
            qr/\breg\s+\[2:0\]\s+E;/s,
            qr/\breg\s+\[7:0\]\s+F;/s,
            qr/\breg\s+\[7:0\]\s+G;/s,
            qr/\breg\s+\[8:0\]\s+H;/s,
        ],
    },
    {
        id => 'feature.direct_runtime_div_mod',
        relpath => 't/corpus/direct_runtime_div_mod.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'direct_runtime_div_mod',
        expected_hdl_patterns => [
            qr/\bQUO\s*=\s*A\s*\/\s*B;/s,
            qr/\bREM\s*=\s*A\s*%\s*B;/s,
            qr/\bQUO_ALIAS\s*=\s*A\s*\/\s*B;/s,
            qr/\bREM_ALIAS\s*=\s*A\s*%\s*B;/s,
            qr/\bQUO_CHAIN\s*=\s*A\s*\/\s*B\s*\/\s*C;/s,
            qr/\bREM_CHAIN\s*=\s*A\s*%\s*B\s*%\s*C;/s,
        ],
    },
    {
        id => 'feature.direct_assignment_pair_form',
        relpath => 't/corpus/direct_assignment_pair_form.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'direct_assignment_pair_form',
        expected_hdl_patterns => [
            qr/\bCOMB\s*=\s*SRC;/s,
            qr/\bSUM\s*=\s*A\s*\+\s*B;/s,
            qr/\bHI\s*=\s*DATA\[7:4\];/s,
            qr/\bLO\s*=\s*DATA\[3:0\];/s,
            qr/\boutput\s+reg\s+\[7:0\]\s+next_QN\b/s,
            qr/\boutput\s+reg\s+\[7:0\]\s+QR_r\b/s,
        ],
    },
    {
        id => 'feature.direct_intent_integer_literals',
        relpath => 't/corpus/direct_intent_integer_literals.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'direct_root_pipeline_cli',
        source_kind => 'fsm',
        strict_supported => 1,
        expected_module_name => 'direct_intent_integer_literals',
        expected_hdl_patterns => [
            qr/\bDEC_CODE\s*=\s*5'd23\s*;/s,
            qr/\bNEG_DEC\s*=\s*8'd246\s*;/s,
            qr/\bNEG_HEX\s*=\s*8'hF6\s*;/s,
            qr/\bNEG_BIN\s*=\s*8'b11110110\s*;/s,
            qr/\bHEX_ALIAS\s*=\s*20'h1\s*;/s,
            qr/\bFROM_CONST\s*=\s*8'hF6\s*;/s,
        ],
    },
    {
        id => 'feature.composition_intent_integer_literals',
        relpath => 't/corpus/composition_intent_integer_literals.fsm',
        family => 'language_feature_fixture',
        classification => 'supported_smoke',
        coverage => 'composition_top_pipeline_cli',
        source_kind => 'composition',
        strict_supported => 1,
        expected_top_name => 'composition_intent_integer_literals',
        expected_lane => 'C3',
        expected_instance_count => 1,
        expected_child_modules => [],
        expected_hdl_patterns => [
            qr/assign\s+decimal_out\s*=\s*5'b10111\s*;/s,
            qr/assign\s+negative_out\s*=\s*8'b11110110\s*;/s,
            qr/assign\s+packed_out\s*=\s*\{5'b10111,\s*8'b11110110,\s*20'b00000000000000000001\}\s*;/s,
            qr/\.decimal_in\(5'b10111\)/s,
            qr/\.negative_in\(8'b11110110\)/s,
            qr/\.packed_in\(\{5'b10111,\s*8'b11110110,\s*20'b00000000000000000001\}\)/s,
        ],
    },
    {
        id => 'legacy.mipicsi2_txccore_ulp.default_compat',
        relpath => 'fsm/mipicsi2_txccore_ulp.fsm',
        family => 'legacy_fixture',
        classification => 'legacy_out_of_scope',
        coverage => 'legacy_root_default_pipeline_cli',
        source_kind => 'fsm',
        expected_module_name => 'mipicsi2_txccore_ulp',
    },
    {
        id => 'legacy.mipicsi2_txccore_ulp.strict_rejection',
        relpath => 'fsm/mipicsi2_txccore_ulp.fsm',
        family => 'legacy_fixture',
        classification => 'expected_failure',
        coverage => 'strict_root_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_STRICT_LEGACY_FSM_ROOT',
        expected_error_pattern => qr/Strict mode rejects the legacy '\+fsm' root family/,
        expected_hint_pattern => qr/\?fsm:module_name/,
    },
    {
        id => 'legacy.empty_size_noop.default_compat',
        relpath => 't/corpus/legacy_empty_size_noop.fsm',
        family => 'legacy_fixture',
        classification => 'legacy_out_of_scope',
        coverage => 'legacy_section_default_pipeline_cli',
        source_kind => 'fsm',
        expected_module_name => 'legacy_empty_size_noop',
    },
    {
        id => 'legacy.empty_size_noop.strict_rejection',
        relpath => 't/corpus/legacy_empty_size_noop.fsm',
        family => 'legacy_fixture',
        classification => 'expected_failure',
        coverage => 'strict_section_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_STRICT_EMPTY_SIZE_SECTION',
        expected_error_pattern => qr/Strict mode rejects the legacy empty '\(\+size\)' section/,
        expected_hint_pattern => qr/replace it with explicit '\(\+size \(signal width\) \.\.\.\)' entries/,
    },
    {
        id => 'legacy.asreset_rstn.default_compat',
        relpath => 't/corpus/legacy_asreset_rstn.fsm',
        family => 'legacy_fixture',
        classification => 'legacy_out_of_scope',
        coverage => 'legacy_section_default_pipeline_cli',
        source_kind => 'fsm',
        expected_module_name => 'legacy_asreset_rstn',
    },
    {
        id => 'legacy.asreset_rstn.strict_rejection',
        relpath => 't/corpus/legacy_asreset_rstn.fsm',
        family => 'legacy_fixture',
        classification => 'expected_failure',
        coverage => 'strict_section_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_STRICT_MISLEADING_ARESET_RSTN',
        expected_error_pattern => qr/Strict mode rejects the legacy or misleading '\(asreset rstn\)' \+system spelling.*Use '\(sreset reset\)' for synchronous active-high reset or '\(areset rst_n\)' for asynchronous active-low reset/s,
        expected_hint_pattern => qr/\(sreset reset\).*\(areset rst_n\)/s,
    },
    {
        id => 'legacy.sreset_rstn.default_compat',
        relpath => 't/corpus/legacy_sreset_rstn.fsm',
        family => 'legacy_fixture',
        classification => 'legacy_out_of_scope',
        coverage => 'legacy_section_default_pipeline_cli',
        source_kind => 'fsm',
        expected_module_name => 'legacy_sreset_rstn',
    },
    {
        id => 'legacy.sreset_rstn.strict_rejection',
        relpath => 't/corpus/legacy_sreset_rstn.fsm',
        family => 'legacy_fixture',
        classification => 'expected_failure',
        coverage => 'strict_section_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_STRICT_MISLEADING_SRESET_RSTN',
        expected_error_pattern => qr/Strict mode rejects the legacy or misleading '\(sreset rstn\)' \+system spelling.*Use '\(sreset reset\)' for synchronous active-high reset or '\(areset rst_n\)' for asynchronous active-low reset/s,
        expected_hint_pattern => qr/\(sreset reset\).*\(areset rst_n\)/s,
    },
    {
        id => 'legacy.compact_init_directive.default_compat',
        relpath => 't/corpus/legacy_compact_init_directive.fsm',
        family => 'legacy_fixture',
        classification => 'legacy_out_of_scope',
        coverage => 'legacy_section_default_pipeline_cli',
        source_kind => 'fsm',
        expected_module_name => 'legacy_compact_init_directive',
    },
    {
        id => 'legacy.compact_init_directive.strict_rejection',
        relpath => 't/corpus/legacy_compact_init_directive.fsm',
        family => 'legacy_fixture',
        classification => 'expected_failure',
        coverage => 'strict_section_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_STRICT_COMPACT_INIT_DIRECTIVE',
        expected_error_pattern => qr/Strict mode rejects the legacy compact '\(:= signal=value\)' top-level directive.*Use the canonical '\(:= \(signal value\)\)' form.*compact ':=' surface/s,
        expected_hint_pattern => qr/Use the canonical '\(:= \(signal value\)\)' form/s,
    },
    {
        id => 'legacy.infix_assignment.default_compat',
        relpath => 't/corpus/legacy_infix_assignment.fsm',
        family => 'legacy_fixture',
        classification => 'legacy_out_of_scope',
        coverage => 'legacy_assignment_default_pipeline_cli',
        source_kind => 'fsm',
        expected_module_name => 'legacy_infix_assignment',
    },
    {
        id => 'legacy.infix_assignment.strict_rejection',
        relpath => 't/corpus/legacy_infix_assignment.fsm',
        family => 'legacy_fixture',
        classification => 'expected_failure',
        coverage => 'strict_assignment_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_STRICT_INFIX_ASSIGNMENT',
        expected_error_pattern => qr/Strict mode rejects infix assignment '\(OUT = SRC\)'.*Use the canonical pair form '\(= \(OUT SRC\)\)'.*infix assignment compatibility/s,
        expected_hint_pattern => qr/Use the canonical pair form '\(= \(OUT SRC\)\)'/s,
    },
    {
        id => 'legacy.lteplus_assignment.default_compat',
        relpath => 't/corpus/legacy_lteplus_assignment.fsm',
        family => 'legacy_fixture',
        classification => 'legacy_out_of_scope',
        coverage => 'legacy_assignment_default_pipeline_cli',
        source_kind => 'fsm',
        expected_module_name => 'legacy_lteplus_assignment',
    },
    {
        id => 'legacy.lteplus_assignment.strict_rejection',
        relpath => 't/corpus/legacy_lteplus_assignment.fsm',
        family => 'legacy_fixture',
        classification => 'expected_failure',
        coverage => 'strict_assignment_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_STRICT_LEGACY_LTEPLUS_ASSIGNMENT',
        expected_error_pattern => qr/Strict mode rejects legacy '<=\+' assignment '\(<\=\+ \(D_IN NEXT_VALUE\)\)'.*Use the preferred '<=-' pair form '\(<\=- \(D_IN NEXT_VALUE\)\)'.*'<=\+' compatibility/s,
        expected_hint_pattern => qr/Use the preferred '<=-' pair form '\(<\=- \(D_IN NEXT_VALUE\)\)'/s,
    },
    {
        id => 'legacy.fsm_child_root.default_compat',
        relpath => 't/corpus/legacy_fsm_child_root_top.fsm',
        family => 'legacy_fixture',
        classification => 'legacy_out_of_scope',
        coverage => 'legacy_child_root_default_pipeline_cli',
        source_kind => 'composition',
        search_path_relpaths => ['t/corpus'],
        expected_top_name => 'legacy_fsm_child_root_top',
        expected_lane => 'C1',
        expected_instance_count => 1,
        expected_child_modules => ['legacy_fsm_child_root_src'],
    },
    {
        id => 'legacy.fsm_child_root.strict_rejection',
        relpath => 't/corpus/legacy_fsm_child_root_top.fsm',
        family => 'legacy_fixture',
        classification => 'expected_failure',
        coverage => 'strict_child_root_rejection_pipeline_cli',
        source_kind => 'composition',
        search_path_relpaths => ['t/corpus'],
        diagnostic_code => 'FSMGEN_STRICT_FSMC_LEGACY_ROOT',
        expected_error_pattern => qr/Generated child source:\s+'\?fsmc' 'legacy_fsm_child_root_src'.*Strict mode rejects the legacy '\+fsm' root family as the root of '\?fsmc' source 'legacy_fsm_child_root_src'/s,
        expected_hint_pattern => qr/\?fsm:source_name/,
    },
    {
        id => 'legacy.dt_child_root.default_compat',
        relpath => 't/corpus/legacy_dt_child_root_top.fsm',
        family => 'legacy_fixture',
        classification => 'legacy_out_of_scope',
        coverage => 'legacy_child_root_default_pipeline_cli',
        source_kind => 'composition',
        search_path_relpaths => ['t/corpus'],
        expected_top_name => 'legacy_dt_child_root_top',
        expected_lane => 'C1',
        expected_instance_count => 1,
        expected_child_modules => ['legacy_dt_child_root_src'],
    },
    {
        id => 'legacy.dt_child_root.strict_rejection',
        relpath => 't/corpus/legacy_dt_child_root_top.fsm',
        family => 'legacy_fixture',
        classification => 'expected_failure',
        coverage => 'strict_child_root_rejection_pipeline_cli',
        source_kind => 'composition',
        search_path_relpaths => ['t/corpus'],
        diagnostic_code => 'FSMGEN_STRICT_DTC_CHILD_ROOT',
        expected_error_pattern => qr/Generated child source:\s+'\?dtc' 'legacy_dt_child_root_src'.*Strict mode rejects '\?module:legacy_dt_child_root_src' as the root of '\?dtc' source 'legacy_dt_child_root_src'/s,
        expected_hint_pattern => qr/\?dt:source_name/,
    },
    {
        id => 'contract.language_contract_bad_size_entry',
        relpath => 't/corpus/language_contract_bad_size_entry.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_BAD_SIZE_ENTRY',
        expected_error_pattern => qr/Malformed '\+size' entry/,
    },
    {
        id => 'contract.direct_size_expression_non_positive',
        relpath => 't/corpus/direct_size_expression_non_positive.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_NON_POSITIVE_SIZE',
        expected_error_pattern => qr/Malformed '\+size' entry for signal 'OUT'.*must resolve to a positive integer width/s,
    },
    {
        id => 'contract.direct_size_expression_unknown_symbol',
        relpath => 't/corpus/direct_size_expression_unknown_symbol.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_UNKNOWN_SIZE_SYMBOL',
        expected_error_pattern => qr/Malformed '\+size' entry for signal 'OUT'.*references unknown or non-scalar constant symbol 'MISSING_W'/s,
    },
    {
        id => 'contract.direct_size_expression_aggregate_symbol',
        relpath => 't/corpus/direct_size_expression_aggregate_symbol.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_AGGREGATE_SIZE_SYMBOL',
        expected_error_pattern => qr/Malformed '\+size' entry for signal 'OUT'.*symbol 'WIDTHS' resolved to aggregate payload kind 'list', not a scalar integer/s,
    },
    {
        id => 'contract.direct_size_expression_divide_by_zero',
        relpath => 't/corpus/direct_size_expression_divide_by_zero.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_SIZE_DIVIDE_BY_ZERO',
        expected_error_pattern => qr/Malformed '\+size' entry for signal 'OUT'.*divides by zero in a width expression/s,
    },
    {
        id => 'contract.direct_size_expression_modulo_by_zero',
        relpath => 't/corpus/direct_size_expression_modulo_by_zero.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_SIZE_MODULO_BY_ZERO',
        expected_error_pattern => qr/Malformed '\+size' entry for signal 'OUT'.*takes modulo by zero in a width expression/s,
    },
    {
        id => 'contract.direct_size_expression_unsupported_operator',
        relpath => 't/corpus/direct_size_expression_unsupported_operator.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_UNSUPPORTED_SIZE_OPERATOR',
        expected_error_pattern => qr/Malformed '\+size' entry for signal 'OUT'.*uses unsupported width expression operator 'pow'/s,
    },
    {
        id => 'contract.direct_size_expression_bad_arity',
        relpath => 't/corpus/direct_size_expression_bad_arity.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_SIZE_OPERATOR_ARITY',
        expected_error_pattern => qr/Malformed '\+size' entry for signal 'OUT'.*operator '\+' requires at least two operands/s,
    },
    {
        id => 'contract.direct_lhs_deconstruct_width_mismatch',
        relpath => 't/corpus/direct_lhs_deconstruct_width_mismatch.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_LHS_DECONSTRUCT_WIDTH',
        expected_error_pattern => qr/LHS deconstruct total width 8 does not match RHS width 7/s,
    },
    {
        id => 'contract.unsupported_top_level_define_source',
        relpath => 't/corpus/unsupported_top_level_define_source.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'unknown',
        diagnostic_code => 'FSMGEN_LANGUAGE_UNSUPPORTED_TOP_LEVEL_SOURCE',
        expected_error_pattern => qr/Unsupported top-level source '\?define:legacy_template'/s,
    },
    {
        id => 'contract.unsupported_top_level_clock_directive',
        relpath => 't/corpus/unsupported_top_level_clock_directive.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_UNSUPPORTED_TOP_LEVEL_DIRECTIVE',
        expected_error_pattern => qr/Unsupported top-level directive '\+clock'/s,
    },
    {
        id => 'contract.generic_placeholder_selector',
        relpath => 't/corpus/generic_placeholder_selector.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_GENERIC_PLACEHOLDER_SELECTOR',
        expected_error_pattern => qr/Unsupported generic\/template test selector '\?\[READ\]'/s,
    },
    {
        id => 'contract.generic_repeat_macro',
        relpath => 't/corpus/generic_repeat_macro.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_GENERIC_REPEAT_ACTION',
        expected_error_pattern => qr/Unsupported generic\/template repeat action '\?repeat:\[MAX_COUNT\]'/s,
    },
    {
        id => 'contract.generic_placeholder_token',
        relpath => 't/corpus/generic_placeholder_token.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_GENERIC_PLACEHOLDER_TOKEN',
        expected_error_pattern => qr/Unsupported generic\/template placeholder token '\[DATAIN\]'/s,
    },
    {
        id => 'contract.bare_assignment_condition_suffix',
        relpath => 't/corpus/bare_assignment_condition_suffix.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_BARE_CONDITION_SUFFIX',
        expected_error_pattern => qr/Unsupported bare condition suffix 'start'/s,
    },
    {
        id => 'contract.bare_transition_condition_suffix',
        relpath => 't/corpus/bare_transition_condition_suffix.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_BARE_CONDITION_SUFFIX',
        expected_error_pattern => qr/Unsupported bare condition suffix 'full'/s,
    },
    {
        id => 'contract.malformed_top_level_system_root',
        relpath => 't/corpus/malformed_top_level_system_root.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'unknown',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_SOURCE_ROOT',
        expected_error_pattern => qr/Malformed top-level source root '\+system'/s,
    },
    {
        id => 'contract.malformed_single_token_action',
        relpath => 't/corpus/malformed_single_token_action.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_UNSUPPORTED_ACTION_FORM',
        expected_error_pattern => qr/Unsupported action form '\(BROKEN\)'/s,
    },
    {
        id => 'contract.malformed_empty_guard',
        relpath => 't/corpus/malformed_empty_guard.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_GUARDED_BLOCK',
        expected_error_pattern => qr/Malformed guarded block '<req'/s,
    },
    {
        id => 'contract.malformed_empty_test_branch',
        relpath => 't/corpus/malformed_empty_test_branch.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_TEST_BRANCH',
        expected_error_pattern => qr/Malformed test branch '=0'/s,
    },
    {
        id => 'contract.malformed_bare_symbolic_test_selector',
        relpath => 't/corpus/malformed_bare_symbolic_test_selector.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_TEST_SELECTOR',
        expected_error_pattern => qr/Malformed test selector 'BUSY'/s,
    },
    {
        id => 'contract.malformed_bare_numeric_test_selector',
        relpath => 't/corpus/malformed_bare_numeric_test_selector.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_TEST_SELECTOR',
        expected_error_pattern => qr/Malformed test selector '0'/s,
    },
    {
        id => 'contract.system_incomplete_section',
        relpath => 't/corpus/system_incomplete_section.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_INCOMPLETE_SYSTEM_SECTION',
        expected_error_pattern => qr/Incomplete '\+system' section/s,
    },
    {
        id => 'contract.system_duplicate_clock_entry',
        relpath => 't/corpus/system_duplicate_clock_entry.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_DUPLICATE_SYSTEM_ENTRY',
        expected_error_pattern => qr/Duplicate '\+system' entry 'clock'/s,
    },
    {
        id => 'contract.system_duplicate_reset_declaration',
        relpath => 't/corpus/system_duplicate_reset_declaration.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_DUPLICATE_SYSTEM_RESET',
        expected_error_pattern => qr/Duplicate '\+system' reset declaration 'areset'/s,
    },
    {
        id => 'contract.system_malformed_entry_structure',
        relpath => 't/corpus/system_malformed_entry_structure.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_SYSTEM_ENTRY',
        expected_error_pattern => qr/Unsupported '\+system' entry structure/s,
    },
    {
        id => 'contract.system_bad_clock_identifier',
        relpath => 't/corpus/system_bad_clock_identifier.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_BAD_SYSTEM_CLOCK_NAME',
        expected_error_pattern => qr/Unsupported '\+system' clock name 'core-clk'/s,
    },
    {
        id => 'contract.system_bad_reset_identifier',
        relpath => 't/corpus/system_bad_reset_identifier.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_BAD_SYSTEM_RESET_NAME',
        expected_error_pattern => qr/Unsupported '\+system' reset name 'reset-name'/s,
    },
    {
        id => 'contract.malformed_fsm_source_name',
        relpath => 't/corpus/malformed_fsm_source_name.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_FSM_SOURCE_NAME',
        expected_error_pattern => qr/Malformed top-level FSM source '\?fsm:bad-name'/s,
    },
    {
        id => 'contract.malformed_top_source_name',
        relpath => 't/corpus/malformed_top_source_name.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_TOP_SOURCE_NAME',
        expected_error_pattern => qr/Malformed composition top root '\?top:bad-name'/s,
    },
    {
        id => 'contract.malformed_state_name',
        relpath => 't/corpus/malformed_state_name.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_STATE_NAME',
        expected_error_pattern => qr/Malformed state\/DT name 'bad-name'/s,
    },
    {
        id => 'contract.malformed_standalone_dt_name',
        relpath => 't/corpus/malformed_standalone_dt_name.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_STATE_NAME',
        expected_error_pattern => qr/Malformed state\/DT name '-bad-name'/s,
    },
    {
        id => 'contract.malformed_transition_target',
        relpath => 't/corpus/malformed_transition_target.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MALFORMED_TRANSITION_TARGET',
        expected_error_pattern => qr/Malformed transition target 'bad-name'/s,
    },
    {
        id => 'contract.unknown_transition_target',
        relpath => 't/corpus/unknown_transition_target.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_UNKNOWN_TRANSITION_TARGET',
        expected_error_pattern => qr/Unknown transition target 'missing_state' from state\/DT 'idle'/s,
    },
    {
        id => 'contract.assignment_delayed_pulse_bad_rhs',
        relpath => 't/corpus/assignment_delayed_pulse_bad_rhs.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_DELAYED_PULSE_RHS',
        expected_error_pattern => qr/Malformed delayed pulse RHS 'B'.*1-bit literal RHS/s,
    },
    {
        id => 'contract.assignment_mixed_comb_seq',
        relpath => 't/corpus/assignment_mixed_comb_seq.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MIXED_ASSIGNMENT_FAMILIES',
        expected_error_pattern => qr/Mixed combinational '=' and sequential operators/s,
    },
    {
        id => 'contract.assignment_mixed_pulse_nonpulse',
        relpath => 't/corpus/assignment_mixed_pulse_nonpulse.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MIXED_PULSE_ASSIGNMENT_FAMILY',
        expected_error_pattern => qr/Mixed pulse-delayed and non-pulse sequential operators/s,
    },
    {
        id => 'contract.assignment_multiple_pulse_delays',
        relpath => 't/corpus/assignment_multiple_pulse_delays.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_MULTIPLE_PULSE_DELAYS',
        expected_error_pattern => qr/Multiple pulse delays .* unsupported/s,
    },
    {
        id => 'contract.assignment_comb_self_dependency',
        relpath => 't/corpus/assignment_comb_self_dependency.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_COMBINATIONAL_SELF_DEPENDENCY',
        expected_error_pattern => qr/Illegal combinational self-dependency/s,
    },
    {
        id => 'contract.assignment_d_input_self_dependency',
        relpath => 't/corpus/assignment_d_input_self_dependency.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_D_INPUT_SELF_DEPENDENCY',
        expected_error_pattern => qr/Illegal D-input self-dependency/s,
    },
    {
        id => 'contract.operator_unsupported_qeq',
        relpath => 't/corpus/operator_unsupported_qeq.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_UNSUPPORTED_ASSIGNMENT_OPERATOR',
        expected_error_pattern => qr/Unsupported assignment operator '\?=' for signal 'A'/s,
    },
    {
        id => 'contract.operator_unsupported_arrow',
        relpath => 't/corpus/operator_unsupported_arrow.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_UNSUPPORTED_ASSIGNMENT_OPERATOR',
        expected_error_pattern => qr/Unsupported assignment operator '=>' for signal 'A'/s,
    },
    {
        id => 'contract.directive_init_placeholder_value',
        relpath => 't/corpus/directive_init_placeholder_value.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_UNSUPPORTED_INIT_RESET_VALUE',
        expected_error_pattern => qr/Unsupported ':=' reset value '\[DATAIN\]' for signal 'tester_reset'/s,
    },
    {
        id => 'contract.directive_init_guard_value',
        relpath => 't/corpus/directive_init_guard_value.fsm',
        family => 'language_contract_fixture',
        classification => 'expected_failure',
        coverage => 'language_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_LANGUAGE_UNSUPPORTED_INIT_RESET_VALUE',
        expected_error_pattern => qr/Unsupported ':=' reset value '<start' for signal 'tester_reset'/s,
    },
    {
        id => 'contract.direct_rhs_concat_width_mismatch',
        relpath => 't/corpus/direct_rhs_concat_width_mismatch.fsm',
        family => 'direct_generation_contract_fixture',
        classification => 'expected_failure',
        coverage => 'direct_generation_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_DIRECT_RHS_WIDTH_MISMATCH',
        expected_error_pattern => qr/assignment to 'BUS' uses RHS '\{HI, LO\}' with incompatible width 7 for LHS width 8; .*implicit widening/s,
    },
    {
        id => 'contract.direct_aggregate_contract_mismatch',
        relpath => 't/corpus/direct_aggregate_contract_mismatch.fsm',
        family => 'direct_generation_contract_fixture',
        classification => 'expected_failure',
        coverage => 'direct_generation_contract_rejection_pipeline_cli',
        source_kind => 'fsm',
        diagnostic_code => 'FSMGEN_DIRECT_AGGREGATE_CONTRACT_MISMATCH',
        expected_error_pattern => qr/assignment to 'OUT' uses whole aggregate RHS 'FRAME' with contract 'record\{mode:bits\[2\], flag:bit\}' that does not match declared type 'list<bit, bits\[2\]>'/s,
    },
    {
        id => 'contract.missing_rtl_metadata_sidecar',
        relpath => 't/corpus/missing_rtl_metadata_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_COMPOSITION_MISSING_RTLIF',
        expected_error_pattern => qr/Expected RTL metadata file:\s+'uart_tx\.rtlif'.*RTL child module:\s+'\?rtl' 'uart_tx'.*no declared interface metadata file 'uart_tx\.rtlif' was found/s,
    },
    {
        id => 'contract.missing_fsm_child_source',
        relpath => 't/corpus/missing_fsm_child_source_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_COMPOSITION_MISSING_FSM_CHILD',
        expected_error_pattern => qr/Expected child source file:\s+'missing_src\.fsm'.*Generated child source:\s+'\?fsmc' 'missing_src'.*child-source resolution is blocked because no active child FSM source was found either embedded in the same file or in an external '\.fsm' file/s,
    },
    {
        id => 'contract.missing_dt_child_source',
        relpath => 't/corpus/missing_dt_child_source_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_COMPOSITION_MISSING_DT_CHILD',
        expected_error_pattern => qr/Expected child source file:\s+'missing_dt_src\.fsm'.*Generated child source:\s+'\?dtc' 'missing_dt_src'.*child-source resolution is blocked because no active standalone-DT child source was found either embedded in the same file or in an external '\.fsm' file/s,
    },
    {
        id => 'contract.invalid_rtl_system_port_direction',
        relpath => 't/corpus/invalid_rtl_system_direction_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_RTLIF_SYSTEM_PORT_DIRECTION',
        expected_error_pattern => qr/RTL metadata file:\s+'.*invalid_sysdir_uart_tx\.rtlif'.*RTL child module:\s+'\?rtl' 'invalid_sysdir_uart_tx'.*RTL interface metadata system-port direction is blocked because token 'core_clk>:clock' in declared interface metadata '.*invalid_sysdir_uart_tx\.rtlif' resolves to 'clock' while declaring an output direction/s,
    },
    {
        id => 'contract.duplicate_rtlif_port_declaration',
        relpath => 't/corpus/duplicate_rtlif_port_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_RTLIF_DUPLICATE_PORT',
        expected_error_pattern => qr/RTL metadata file:\s+'.*duplicate_port_uart_tx\.rtlif'.*RTL child module:\s+'\?rtl' 'duplicate_port_uart_tx'.*RTL interface metadata port declaration uniqueness is blocked because declared interface metadata '.*duplicate_port_uart_tx\.rtlif' repeats port 'txd'/s,
    },
    {
        id => 'contract.invalid_rtlif_port_type',
        relpath => 't/corpus/invalid_rtlif_port_type_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_RTLIF_UNSUPPORTED_PORT_TYPE',
        expected_error_pattern => qr/RTL metadata file:\s+'.*invalid_type_uart_tx\.rtlif'.*RTL child module:\s+'\?rtl' 'invalid_type_uart_tx'.*RTL interface metadata port typing is blocked because token 'data_in<8:status' in declared interface metadata '.*invalid_type_uart_tx\.rtlif' resolves to unsupported port type 'status'/s,
    },
    {
        id => 'contract.invalid_rtlif_port_token',
        relpath => 't/corpus/invalid_rtlif_port_token_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_RTLIF_INVALID_PORT_TOKEN',
        expected_error_pattern => qr/RTL metadata file:\s+'.*invalid_token_uart_tx\.rtlif'.*RTL child module:\s+'\?rtl' 'invalid_token_uart_tx'.*RTL interface metadata token shape is blocked because token 'data-in<8:data' in declared interface metadata '.*invalid_token_uart_tx\.rtlif' is an invalid port token/s,
    },
    {
        id => 'contract.invalid_rtlif_port_width',
        relpath => 't/corpus/invalid_rtlif_port_width_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_RTLIF_NON_POSITIVE_PORT_WIDTH',
        expected_error_pattern => qr/RTL metadata file:\s+'.*invalid_width_uart_tx\.rtlif'.*RTL child module:\s+'\?rtl' 'invalid_width_uart_tx'.*RTL interface metadata port sizing is blocked because token 'data_in<0:data' in declared interface metadata '.*invalid_width_uart_tx\.rtlif' declares non-positive port width '0'/s,
    },
    {
        id => 'contract.missing_rtlif_root',
        relpath => 't/corpus/missing_rtlif_root_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_RTLIF_MISSING_ROOT',
        expected_error_pattern => qr/RTL interface metadata structure is blocked because declared interface metadata '.*missing_root_uart_tx\.rtlif' does not contain a '\?rtlif:missing_root_uart_tx' root\./s,
    },
    {
        id => 'contract.empty_rtlif_port_declaration',
        relpath => 't/corpus/empty_rtlif_port_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_RTLIF_EMPTY_PORTS',
        expected_error_pattern => qr/RTL interface metadata port presence is blocked because declared interface metadata '.*empty_port_uart_tx\.rtlif' declares no ports under '\?rtlif:empty_port_uart_tx'\./s,
    },
    {
        id => 'contract.nested_rtlif_port_declaration',
        relpath => 't/corpus/nested_rtlif_port_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_RTLIF_NESTED_STRUCTURE',
        expected_error_pattern => qr/RTL interface metadata flatness is blocked because declared interface metadata '.*nested_port_uart_tx\.rtlif' contains nested structure under '\?rtlif:nested_port_uart_tx'\./s,
    },
    {
        id => 'contract.duplicate_embedded_rtlif_root',
        relpath => 't/corpus/duplicate_embedded_rtlif_top.fsm',
        family => 'composition_contract_fixture',
        classification => 'expected_failure',
        coverage => 'composition_contract_rejection_pipeline_cli',
        source_kind => 'composition',
        diagnostic_code => 'FSMGEN_RTLIF_DUPLICATE_EMBEDDED_ROOT',
        expected_error_pattern => qr/RTL interface metadata embedded-root uniqueness is blocked because the active RTL interface contract allows at most one embedded interface root per external RTL module name in the same source\./s,
    },
);

sub regression_corpus_entries {
    return map { _copy_entry($_) } @REGRESSION_CORPUS;
}

sub protocol_fixture_entries {
    return map { _copy_entry($_) } grep { $_->{family} eq 'protocol_fixture' } @REGRESSION_CORPUS;
}

sub _copy_entry {
    my ($entry) = @_;

    return _clone_entry_value($entry);
}

sub _clone_entry_value {
    my ($value) = @_;
    return undef unless defined $value;

    if (ref($value) eq 'HASH') {
        return {
            map { $_ => _clone_entry_value($value->{$_}) } sort keys %{$value}
        };
    }

    if (ref($value) eq 'ARRAY') {
        return [ map { _clone_entry_value($_) } @{$value} ];
    }

    return $value;
}

1;
